### ISSUE TITLE
A nerdside chat about Karai

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#100]
Chat transcript of a convo re: karai brainstorming. looking for ideas. posting here for posterity.

**A SINGLE GREEN NAME - Today at 4:02 AM**
ok so the merge mining logic happens mostly in node-cryptonote-util
I've found some code that's in use currently to merge mine other CN stuff. https://bitcointalk.org/index.php?topic=675107.msg7655813#msg7655813
[ANN] Xmining Pool [BCN/XMR/FCN/QCN/XDN/BBR/DSH/AEON] CryptoNote M...
[ANN] Xmining Pool [BCN/XMR/FCN/QCN/XDN/BBR/DSH/AEON] CryptoNote Merge Mining
woot
It looks like we may have most of what we need already present in TRTL to make good use of TX_extra, but I'm not done looking, as the PR's that added merge mining to XDN all contain about 500 license updates also and I don't know how to discard those when reviewing the commits
I've begun adding in the parts they do have that we don't have. I've added in but commented out part of the ringct logic, and the merge mining logic
we can further expand this later by modifying our block template
basically we can add subtract or modify fields, but it has to be during a fork
we should start thinking of a data policy of what needs to be dictated on TRTL network as far as an acceptable format that our new modified TX_EXTRA will permit in blocks
curently we just let whatever go on in there, and that's not sustainable in the future without impacting just normal transactions
for example, let's put on our imagination hats for a second and think about what a private smart contract reference might look like in a block. we need to communicate an ID of some sort to identify our session with the contract, so we'll need a PID of sorts, we'll need something to indicate which contract we're interacting with, so that can be an address (99 chars) or an openAlias DNS record, so potentially however many characters you can make subdomain.toplevel.tld
then you'll need to share some keys to help decrypt your part of this transaction, which will likely need to rely on multisig transactions to include several parties in the transaction
so lets look at what we have so far
PID, in the interest of being future-compatible, let's assume it's like our current one with 64 character hex: the purpose of this PID is to identify your session with this application for the purposes of returning data to you. Example: You're using a dapp that hosts blog text files or images or something, and in order to associate this with their account on the webfrontend for this, they're provisioned a PID, which they include in the transaction

**madk - TRTL LOYALIST - Today at 4:12 AM**
nice work, that's the benefit of cryptonote, lots of prior work.

A SINGLE GREEN NAME - Today at 4:12 AM
recipient address, it's smart to assume that the contract will live as a script-address, or bot-address, which is a multisig account
ok so then you have to obv transmit some type of proof that you possess the keys to intercept and decode the transaction, so then you have keys
all together the string would be built like this
[pid] [multisig-address-or-openalias-but-lets-assume-99-chars-for-now] [key1] [key2...?]
so I've identified what sessions this data is associated with, I've indicated the recipient of this request, and I've substantiated that I am who I say I am
the app takes this, uses its own key to decrypt the request, then executes whatever logic it contains on the data chain
let's say, in this case, a post gets added to "madk's vegan pizza recipes"(edited)
and we know it's madk and we can trust it because he signed it
let me know if you guys have any ideas. some things I need are: someone from node-cryptonote-util experience like a mining pool operator who has modified it in the past, or someone who's proficient with that type of code. I need someone to bounce ideas off of for this, because I've already got a few iterations of a first sidechain that is designed to just dumbly hold data to say that we can do it

**iburnmycd - Today at 4:18 AM**
But what if I don’t trust madk?

**A SINGLE GREEN NAME - Today at 4:19 AM**
we'll need some kind of web frontend for these tests that shows us the median size for blocks currently, how full are we filling those blocks, and how big can we get in X blocks before an extra cost is incurred for fees
graphs and charts
pretty shit
you dont have to trust madk; in fact I don't think I've ever trusted a vegan in my life

**Turtley McTurtleton McDrizzle - Today at 4:20 AM**
hey I can do that!

**A SINGLE GREEN NAME - Today at 4:20 AM**
boom
ok I've put that on your file

**Turtley McTurtleton McDrizzle - Today at 4:20 AM**
front end badass

**A SINGLE GREEN NAME - Today at 4:21 AM**
those specific data points are things you should be able to source from our current blockchain, and when we port it to the sidechain, we can move it there

**iburnmycd - Today at 4:21 AM**
_leans against the door frame chewing a toothpick_

**A SINGLE GREEN NAME - Today at 4:21 AM**
@iburnmycd get in here :smiley: 

**Turtley McTurtleton McDrizzle - Today at 4:21 AM**
and I do a bunch of enterprise chart reports and analytics shit all the time

**iburnmycd - Today at 4:21 AM**
Lol

**A SINGLE GREEN NAME - Today at 4:21 AM**
yeah man, charts and graphs and stuff always get me a little giddy
im going to put all this on a meta post
brb

**Comment by jerme404** [comment]
Just parking this here so I don't lose it.


RockSteady | Karai - Today at 9:43 PM
right and if possible tell us whats transaction data and what is data from the tx_extra field of the blocks
so basically transactional token exchange vs dapps being stuffed in there

RockSteady | Karai - Today at 9:46 PM
what do you mean
this ideally runs on the karai chain, because that's the only one we're really concerned about knowing the block breakdown on so long as the turtlecoin blocksize isn't getting too big on its own

RockSteady | Karai - Today at 9:48 PM
if you wanted to show the block breakdown of TRTL vs Karai, that owuld be cool if it's all the same amount of work to just add in the second daemon to monitor
something what I have in mind is a pie chart for karai and a pie chart for TRTL and the pie shows the amount of data in tx_extra vs the amount of data in the transaction inputs
and then below that, a line graph with two lines, one respresenting transactional data and one representing tx extra data, and have the graph just show us the last 30 blocks or whatever
If you have something else in mind that's fine with me, I'm not sure what you're capable of, but you are, so let me know and I'm happy to see it

**Comment by brandonlehmann** [comment]
This has been recorded and can be seen in closed issues. Please reopen if required.
