### ISSUE TITLE
Rainborg in language channels

### ISSUE THREAD

**Issue by fexra** [turtlecoin/meta#103]
More of a discussion than a suggestion, but it came to my attention that a reason why users are less active in #nederands besides the fact that most speak fluent English, is that users don't get rewarded shells for being active in #nederlands.

It wouldn't surprise me that if rainborg would be active in the language channels, more activity would take place there. However, the question for me is: do we want that, because 1) other channels, mainly #general, could become less active, and 2) it would require more shells or lower the amount of shells - not sure how rainborg works.

What do you all think?

**Comment by BrandonT42** [comment]
I'd like to hear Rock's view on this as it's something I brought up when we were testing her out, he wanted general to be the face of our discord. How she chooses which channel to tip is weighted, so we could do something like a weight of 1 for language channels, weight of 2 for non language channels, and weight of 3-5 for general, and as long as enough users were active in the last X minutes in the language channel it would be added in when she randomizes.

**Comment by SoreGums** [comment]
the timeout thing probably going to make it rare appearance in the language channels though ;)

**Comment by RocksteadyTC** [comment]
I'm not against it, but I think gums is right.

**Comment by BrandonT42** [comment]
In that case, may as well add them, yeah? Maybe at the same rate as other non-gen channels, then bump gen's weight up by one or so to balance it out

**Comment by SoreGums** [comment]
plus then there is megatip - that might hit the language channels then ;)

**Comment by BrandonT42** [comment]
Consider it done, I worked out the math and channel weights and added all the language channels tonight.
