### ISSUE TITLE
Develop a Testing Procedure

### ISSUE THREAD

**Issue by thinkpol2** [turtlecoin/meta#108]
We need to develop a testing procedure to use before code goes to release.. something that anyone can follow, so we have multiple testers on varied platforms performing the same basic tests. 

An automated testing platform would not be a bad idea either, but maybe that's Krang?

What all should be tested?

Off the top of my head:
- Daemon 
  - Sync from current height and sync from zero
- Wallet
  - Sync from current height and sync from zero
  - Transfers with various mixins, amounts, with and without payment ID
  - Integration with the various GUI wallets

**Comment by SoreGums** [comment]
- need a checklist of functional things to test.
- probably should start an issue in turtlecoin/turtlecoin with a full checklist to run through for a release
- perpared release notes
- prepared blog post
- prepared other media things

some items for a functional checklist

- [ ] create a tag for release as vN.N.N-rcN
- [ ] sync from zero
  - [ ] no snapshot / no checkpoints
    - [ ] windows
    - [ ] linux
    - [ ] osx
  - [ ] checkpoints
    - [ ] windows
    - [ ] linux
    - [ ] osx

- [ ] sync from last release date to current block hieght
  - [ ] no snapshot / no checkpoints
    - [ ] windows
    - [ ] linux
    - [ ] osx
  - [ ] checkpoints
    - [ ] windows
    - [ ] linux
    - [ ] osx

- [ ] simplewallet ok
  - [ ] syncs from 0
  - [ ] resumes sync from last save

**Comment by RocksteadyTC** [comment]
Can daemon connect to local db

Is local DB valid or is resync needed

is Peer ID assigned

is daemon able to sync with no checkpoints

is daemon able to sync with checkpoints

is daemon able to sync from 0 with checkpoints

is daemon able to sync from 0 without checkpoints

can simplewallet connect to local daemon

can simplewallet connection to a remote daemon

can simplewallet & walletd send a transaction with 0 mixin

can simplewallet & walletd send a transaction with 1000 mixin

can simplewallet & walletd send a transaction with 10 mixin

can simplewallet & walletd perform a fusion transaction in a reasonable amount of time

can simplewallet & walletd output keys and seeds

can simplewallet & walletd import and interpret the keys and seeds correctly

can simplewallet & walletd handle RPC interaction

can simplewallet & walletd do a full resent in a reasonable amount of time

**Comment by woodyjon** [comment]
- [ ] GUI's have tested everything and work fine (mainly test of RPC)

**Comment by ZedPea** [comment]
It would be good if we could move this out to another repo or have some coordinator(s) who can fill in these checkpoints, so we can work together as a team to test everything out - Maybe have a repo and make a new branch for each release, or something, make a branch and fill in the template.

**Comment by SoreGums** [comment]
it seems i can tick Rocks checkboxes - so a repo we all have contrib access to is probably all that is needed - so put it as an issue on turtlecoin/turtlecoin if not enough ppl have access to that then will need a new repo ;)

**Comment by SoreGums** [comment]
feel like even if you can tick a box you really need to leave a comment - so maybe just an issue on turtlecoin/turtlecoin is enough, if you can tick boxes, great, if not...

wait, what about

- create a new issue
- master list in the OP
- 1 comment per item
- then just +1 the comment to show you did it

Then can update the master list as +1's come in?

**Comment by ZedPea** [comment]
- [x] Can daemon connect to local db
- [x] Is local DB valid or is resync needed

The below are only for simplewallet, I haven't tested walletd yet

- [x] can simplewallet connect to local daemon
- [x] can simplewallet connect to a remote daemon

Mixin can no longer be specified in simplewallet, all transfers are sent with a default mixin of 7

- [] can simplewallet & walletd send a transaction with 0 mixin
- [] can simplewallet & walletd send a transaction with 1000 mixin
- [] can simplewallet & walletd send a transaction with 10 mixin

- [x] can simplewallet & walletd perform a fusion transaction in a reasonable amount of time
- [x] can simplewallet & walletd output keys and seeds
- [x] can simplewallet & walletd import and interpret the keys and seeds correctly

**Comment by woodyjon** [comment]
I would propose that, before the final testings, a pre-release is made, with the builds for the 3 OS. Then everybody can test the same, final, version and builds. And upon test completion, pre-release is changed to release and code is merged to master.

**Comment by woodyjon** [comment]
And at least 2 users for every OS would test and fill the checklist.

**Comment by RocksteadyTC** [comment]
@chrisedebo

**Comment by brandonlehmann** [comment]
# TurtleCoin vX.Y.Z Test Log

### Project

- [ ] `Version.h.in` updated to correct semver value
- [ ] Release Notes Prepared

### TurtleCoind Tests
- Daemon connects to local DB
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Local DB does not require resync
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Peer ID assigned
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Connections to multiple peers are made
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Daemon able to sync with external checkpoints
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Daemon able to sync without external checkpoints
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
 
### ZedWallet Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS

### Turtle-Service Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- All RPC endpoints and methods are operational
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS

### GUI Wallet Testing
- Connect to local daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS

**Comment by brandonlehmann** [comment]
Added:

- [ ] Notification list of services with integration assembled

**Comment by brandonlehmann** [comment]
Added:

- Daemon stays in sync for 24 hours
  - [ ] Windows
  - [ ] Ubuntu
  - [ ] MacOS

**Comment by ZedPea** [comment]
Need to add -

If a fork is going to be implemented by the release, the forks effects must be test-netted.

**Comment by crappyrules** [comment]
It's a _software upgrade_, not a fork
