### ISSUE TITLE
Terrarium: Turtlecoin Marketplace

### ISSUE THREAD

**Issue by GT3000** [turtlecoin/meta#11]
I think it would be a great idea to perhaps develop an online marketplace that trades in Turtlecoin. Sort've like Bytecoin Market but less ugly. http://bytecoinmarket.com/.

**Comment by krruzic** [comment]
Willing to work on this, writing the backend in django rest framework. I need someone who can do frontend though. And yes, needs to be nicer than that

I have the trtl.me domain so we can host it on market.trtl.me

**Comment by xkasl** [comment]
I can help with or do the front end, I really want to see a site like this I used to use a doge based one alot.

**Comment by brandonlehmann** [comment]
This project, if and when it exists, is outside the scope of the core project. If you do something with this, please submit it for posting in the roundup.
