### ISSUE TITLE
Help us rename Simplewallet

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#111]
@zedpea wrote the current Simplewallet from scratch, and as such, deserves some type of distinction to differentiate it from an app it replaces, the legacy Simplewallet. If he outright refuses to have it renamed, I'll leave it and respeck it, but imo a more distinct name would be better than "simplewallet". 

A few ideas:

- zimplewallet

- turtle-wallet-cli

- zedwallet

- zTurtleWallet

I'll leave it up to zpalmtree to choose whichever he thinks has the most support or just outright reject a name change completely.

**Comment by ZedPea** [comment]
idgaf call it whatever you want broskis

**Comment by brandonlehmann** [comment]
Maybe a special icon as well? Just for funsies.

**Comment by RocksteadyTC** [comment]
I call it zedwallet a lot

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504084-db720186-71d3-11e8-89d5-66884e39524b.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504087-eabc6eec-71d3-11e8-9086-00f51f20e6cb.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504088-f701ed58-71d3-11e8-9ce1-fe96b74bd0ae.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504090-0380eb6a-71d4-11e8-8bf9-5ff9882b8e7c.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504106-706e3980-71d4-11e8-9b6f-afe7e7409ea3.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504111-891c2668-71d4-11e8-969b-c2ae08724118.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504112-941318b0-71d4-11e8-8fbd-8b5e610190db.png)

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504116-dbdc108e-71d4-11e8-8cc2-ba3067619b86.png)

**Comment by Tom7003** [comment]
turtlewallet or trtlwallet ¯\_(ツ)_/¯

**Comment by TRTLAlien** [comment]
It definitely needs to be Zpalm themed in my opinion. He is a really big part of things and is really humble about it for the most part. It makes it fun thinking of something to thank him for all his work. I like ZpalmWallet. Maybe it hits the nail a little too much on the head. But, that's what I know him as so why not?

**Comment by Dreday00** [comment]
I suggest TurtleZWallet   
I agree with Alien on respecting the creator

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/41504234-6a7a88ea-71d8-11e8-9844-8c48204b7c78.png)

**Comment by Dreday00** [comment]
Honestly I thought  TurtleWalletZ was cool but wasn't sure if  "wallet" needed to be the suffix

**Comment by woodyjon** [comment]
I like zedwallet

**Comment by fexra** [comment]
zimplewallet
zedwallet
zwallet
zats'imple :laughing:

**Comment by SoreGums** [comment]
zedwallet, cause z is pronounced zed, haha 😱

**Comment by LeTurt** [comment]
broskis
shellbox
turtlewallet
zzz-wallet
pea-nuts
trtlhodler
zwallet
zedwallet is maybe nice for author ref, i guess this is not wallet used by most normies anyway

**Comment by crappyrules** [comment]
`set_property(TARGET SimpleWallet PROPERTY OUTPUT_NAME "zedwallet")`

**Comment by RocksteadyTC** [comment]
https://github.com/turtlecoin/turtlecoin/pull/297

**Comment by RocksteadyTC** [comment]
Merged. Zedwallet it is.

**Comment by RocksteadyTC** [comment]
@ZedPea we need to do an article/interview together to introduce the change to users so it doesnt confuse them, and also it'd be a good opportunity to link back to your previous interview

**Comment by brandonlehmann** [comment]
Can we close this?
