### ISSUE TITLE
Cleaning up binaries

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#112]
# Proposal for cleaner binary presentation
### Our presentation of the binaries is confusing, and rooted in old procedures, and in some cases causes AV to flag our zipped binaries because they contain the solominer.

Currently we compile and create these binaries by default, every time, for every user, and supply them in the main zip for every release:

#### turtlecoin/turtlecoin -- (default build, cmake .. && make )
- TurtleCoind
- miner
- poolwallet
- zedwallet
- walletd

**OS philosophies aside, what's stopping us from doing this:** 

#### turtlecoin/turtlecoin -- (default build, cmake .. && make pool ) for pools
- TurtleCoind
- zedwallet
- walletd

#### turtlecoin/turtlecoin -- (default build, cmake .. && make ) for normal people
- TurtleCoind
- zedwallet

#### turtlecoin/turtlecoin -- (default build, cmake .. && make solo ) for solo miners
- TurtleCoind
- zedwallet
- solominer

**now if you're still with me... ...what if we do this?**

#### Scenario A (for pools & services)
- let's assume the app is monolithic and walletd becomes TurtleCoin unified app and basically runs everything in this scenario
- `./TurtleCoin` launches daemon in background, presents zedwallet UI to user by default
- `walletd becomes TurtleCoin unified app`
- a positive about this configuration is that the app applies a basic frontend like the current zedwallet, which is the only reason tmk that pools still want legacy-simplewallet over walletd

#### Scenario B (for pools & services)
- let's assume people are afraid of monoliths and want to keep daemon+walletcli divided in this scenario
- TurtleCoind
- zedwallet (because it is basically walletd with a frontend at this point)

#### Scenario A (for regular users)
- let's assume the app is monolithic and walletd basically runs everything in this scenario as "TurtleCoin" unified app.
- `./TurtleCoin` launches daemon in background, presents zedwallet UI to user by default, and solominer becomes a separate binary not supplied with the default make or binary package in Releases, downloaded separately or built with `cmake .. && make solo`

#### Scenario B (for regular users)
- let's assume people are afraid of monoliths and want to keep daemon+walletcli divided in this scenario
- TurtleCoind
- zedwallet
- solominer in a different binary package in Releases, and built using `cmake .. && make solo`

**Comment by brandonlehmann** [comment]
I was actually debating taking a look at splitting this out like some of this until I got distracted by other things.

**Comment by BigslimVdub** [comment]
I delete everything but daemon anyway because I use nest.

**Comment by brandonlehmann** [comment]
Partial completion in https://github.com/turtlecoin/turtlecoin/pull/348

**Comment by brandonlehmann** [comment]
servicewallet ?

**Comment by RocksteadyTC** [comment]
I like that! We could even just call it "services" since most people who have any business using it already know what it does, and those mistakenly launching walletd and having negative experiences are using it because they saw the word "wallet" in the title.

**Comment by rashedmyt** [comment]
agree with @RocksteadyTC

**Comment by brandonlehmann** [comment]
Singular IMO. It provides a singular service. It provides a wallet as a service(tm)

**Comment by brandonlehmann** [comment]
just ```service``` or ```servicewallet``` ?

**Comment by RocksteadyTC** [comment]
If we put wallet in the name, then people click it and have a bad time, I thought we were on the same page when you said singular service

**Comment by BigslimVdub** [comment]
Why not businesswallet?

**Comment by woodyjon** [comment]
`trtlservice`?

**Comment by woodyjon** [comment]
not cool to not consider my comment..

**Comment by crappyrules** [comment]
I kinda like serviced

**Comment by brandonlehmann** [comment]
I agree with @woodyjon a different name is required. service is too generic.

**Comment by RocksteadyTC** [comment]
turtle-services has been added to 0.7.0

**Comment by brandonlehmann** [comment]
It looks to me like the only thing that's left out of this is to allow for the following:

- `make pool` Makes the stuff a pool needs (ie. TurtleCoind & turtle-service)
- `make miner` Makes the stuff a miner needs (ie. TurtleCoind, zedwallet, & miner)
- `make` makes the general stuff a user needs (ie. TurtleCoind & zedwallet)

Correct?

**Comment by brandonlehmann** [comment]
See https://github.com/turtlecoin/turtlecoin/pull/447
