### ISSUE TITLE
Social Media - Marketing Campaign 

### ISSUE THREAD

**Issue by Mackz2000** [turtlecoin/meta#119]
Social Media and Marketing in general is what brings peoples attention to new and uprising things in the world - whilst also driving up aggregate value of the product from investment.

Turtle Coin from my understanding is meant to be accessible to everyone, private from everyone, fast and has great support from all of the 'seasoned-users'. This is all great, something that most people struggle with in the other Crypto-markets, waiting an hour or more to receive BTC is what pushed me away from them. 

However unless we make an active effort to begin to grow the marketing side of this, then turtle coin will always be a small player in a now overcrowded pond. With over 1000 people between here and the discord we are already a growing community! 

Just for an example if all of us put $1 towards a marketing campaign, as long as it was designed and executed properly, $1000 would reach approximately between 20,000-150,000 depending on what channel was chosen to advertise on. Expecting a norm of a 31% click rate, that would give between 6,200 - 46,500 clicking through to a landing page, preferably somewhere where you can download a wallet, and importantly change common currency's, USD/EUR/GBP to TRTL, instead of having to do USD --> BTC --> TRTL, its inefficient and a wast of money due to fees.  This retracts from the "Easy to Use" statement, as it is easy to set up but not to actually own TRTL.  

I would like to see a community effort to have a huge marketing campaign, once items such as the new website are completed, to see if we can drive some traffic towards the site, and have more people either buy or mine TRTL. I have no issue and would enjoy helping spearhead and lead the marketing campaign, I believe firmly in the values and would love to see Turtle Coin get on the map, seeing as we just got on CMC and recognised, we should now strive to get on their Top 100 List, and that is only done by people!

We have the opportunity to grow, now we just need to utilise it.

Thanks my fellow Turtles!

**Comment by fexra** [comment]
What would be the point of marketing a product that is not complete yet? Wouldn't it be wiser to spend resources and time on development and let the product market itself? Your plan just seems to lead to 1) waste of resources, 2) waste of time, 3) destroy brand image and trust and 4) overload our resources with plebs crying about their expected 1000 EOY returns.

**Comment by brandonlehmann** [comment]
I agree. The focus of the project is development, community, utility, and education. If the concept is marketing those goals, I'm all for it. If the marketing aspect is just a gain in market position, I'm vehemently opposed to it. It's a shame that so many people/groups are jaded by the quick cash scheme and focus less on the technology side of things.

**Comment by brandonlehmann** [comment]
Close ?
