### ISSUE TITLE
Upcoming Ubuntu 18.04 LTS "Bionic Beaver"

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#12]
This thread is for tracking development on the Linux development channel tracking "Bionic Beaver", which is Ubuntu's latest LTS. My goal, personally, is to support every Ubuntu LTS until the greater Linux community starts to use primarily another distribution.

**Comment by RocksteadyTC** [comment]
Hoping to make it by April 26th, Final Release,  Ubuntu 18.04

**Comment by brandonlehmann** [comment]
If you still need this, please reopen it.
