### ISSUE TITLE
Cooperational Partnership / enhance community growth 

### ISSUE THREAD

**Issue by DominikBerger01** [turtlecoin/meta#120]
Hi to all, I'm Dominik representative of PECUNIO (reference www.pecun.io)

I came across Turtle coin yesterday while browsing recently added to CMC and we at PECUNIO are really impressed what you guys managed to built up with your 0 funding philosophy. Also btw we got some TRTL ourselves :))

We'd like to have a chat with the founders our representatives to talk about a business partnership as we think we can provide TRTL with a lot of value.

Key facts:

- we have a community of over 70k crypto enthusiasts (built up in our ICO)
-  we have strong partnerships with more than 10 of the top crypto exchanges (where some of them might list TRTL for free or with a small fee or airdrop) 
- our VC fund has a magnitude of 35 M USD nominal value with active co investors and partners that can either use Turtle or enhance it to the next level. 

and many more. 

Looking forward if someone can lead us to the right source to talk to. 

I'm also reachable at dominik@pecun.io or Telegram  username DominikBerger

All the best, 
Dominik

**Comment by fexra** [comment]
There is a reason why we are doing well without any funding, partnerships, bribes or extortion. We would like to keep it that way. If you would like to present an idea post it here or our subreddit and share it with the Discord, Twitter and Github community.

**Comment by brandonlehmann** [comment]
I tend to agree and echo the statements of @SoreGums and @fexra.

Out in the open is where these discussions belong. It's a community project and the community needs to weigh in their thoughts on such discussions.

**Comment by brandonlehmann** [comment]
Close this please.
