### ISSUE TITLE
Transaction Absent in Transaction Pool

### ISSUE THREAD

**Issue by 2acoin** [turtlecoin/meta#121]
I have a local copy of TurtleCoin daemon running and a copy of Turtle-Pool connected to it with a miner running and mining.

Everything is working fine with the exception of an occasional WARNING message stating;

`
The transaction ################ is absent in the transaction pool.
` 

The ### represent a transaction id...

Anyone know why these errors occur and how I can minimize them?

**Comment by brandonlehmann** [comment]
You'll receive those messages if you receive a new block that contains a transaction that you didn't know have in your transaction mempool. This is typically the result of latency between you and the rest of the network or another communication problem that prevented your daemon from having a full copy of the mempool.

**Comment by 2acoin** [comment]
Thank you for the explanation @brandonlehmann !

**Comment by brandonlehmann** [comment]
Please close this
