### ISSUE TITLE
Database Candidates for CantiLib / cs-turtlecoin

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#122]
Let's make a list of DB candidates so we don't forget

**Comment by jerme404** [comment]
Some NoSQL document store that's stupid fast.  Then again, if you can get the data from an API, I'm not sure the storage layer matters as much.

Where you need a server, I really really like couchbase.  I think nedb and pouchdb are both excellent for embedded options.

**Comment by brandonlehmann** [comment]
This is a cross with #104
