### ISSUE TITLE
getting forking tired of this shit

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#123]
Let's remove all references to the word "fork" in all of our docs and software, as it confuses the user. We should call it what it is, an "upgrade". Fork should be a word resolved for copying the code base, and eating fine steak.

**Comment by brandonlehmann** [comment]
I dare say I actually disagree. 

The chain does actually fork at major changes. Technically speaking, any change to how consensus is determined results in the chain forking as the old path the chain was on could technically still exist. See that poor soul stuck at 620009 as they are on a different chain.

**Comment by brandonlehmann** [comment]
Someone wrote an article that solves this issue... https://blog.turtlecoin.lol/archives/what-the-fork/
