### ISSUE TITLE
TurtleCoin derivation path

### ISSUE THREAD

**Issue by woodyjon** [turtlecoin/meta#127]
Multi coins wallets (like ledger, coinomi, jaxx, trezor...) use a master private key and derive from it private keys for every coins they support. (see [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) and [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki))

For that, we use derivation paths in the form of `/ purpose' / coin_type' / account' / change / address_index`.
coin_type is specific to the coin and should be set as a standard so every wallets use the same.

This page, [SLIP-44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md), registers all the coins that want to follow that standard (and want to be included in multi coins wallets).

We must choose an index for TurtleCoin and get it added to that list (they say we must first have a working multi coin wallet using it before they add it to the list. We will soon have it with the ledger).

Bitcoin is 0. Monero is 128.

When I mentioned this in the discord, cision proposed **1984** (which is available). I started using this for the ledger. But I could still change it.

Let us agree on an index and request it to be added to the SLIP44.

**Comment by RocksteadyTC** [comment]
bump

**Comment by brandonlehmann** [comment]
1984 is good IMO

**Comment by RocksteadyTC** [comment]
I kinda like that

**Comment by RocksteadyTC** [comment]
@woodyjon let's use that

**Comment by woodyjon** [comment]
https://github.com/satoshilabs/slips/pull/400

**Comment by woodyjon** [comment]
Above PR was merged into master!

**Comment by RocksteadyTC** [comment]
Wooh!

**Comment by mcfang** [comment]
Does anyone know what the network parameters would be for TurtleCoin? For example the network parameters for BTC are as follows: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/networks.js
I'm trying to add TurtleCoin to a bitcoinjs-lib project.

**Comment by brandonlehmann** [comment]
As explain on discord, we aren’t bip32. You’ll find much difficulty getting that library to work here.
