### ISSUE TITLE
turle explorer api

### ISSUE THREAD

**Issue by dzefrej0** [turtlecoin/meta#135]
Hi guys, I`m new here and just started learnin about cryptoCurrencies, so please be tolerant :) 
I need to make a project that can consume api of turtlecoin.
Here are the pools :
http://explorer.turtlecoin.lol/pools.html

I need to read hashRate of theese pools, but I don`t know what is the API of the pools?

Can you give me example of endpoint or something with I can start ?

I have read: https://api-docs.turtlecoin.lol/
but I don't quite understant it. Given examples are hosted on the localhost, I want to just read data of given pools from theirs Restfull api
Thanks for every answer in advance. **Happy new Year!**

**Comment by fexra** [comment]
List of pools with API: https://github.com/turtlecoin/turtlecoin-pools-json/blob/master/v2/turtlecoin-pools.json
Pool software reference: https://github.com/turtlecoin/node-turtle-pool

**Comment by dzefrej0** [comment]
thanks a lot! This is it.
