### ISSUE TITLE
идеи

### ISSUE THREAD

**Issue by wolfimen** [turtlecoin/meta#138]
Hi! I want to make a crane free distribution of turtles (turtle). Who can I talk to about this?

**Comment by zpalmtree** [comment]
I think something is getting lost in translation. What does "crane free distribution of turtles" mean?

**Comment by wolfimen** [comment]
Я имел в виду кран\fauset. Бесплатная раздача черепашек, за разгадку капчи.
Мне кажется новым пользователям это было бы полезно. Я могу сделать
кранс\сайт, но не знаю как привязать платежи. Думаю что для нашего
сообщества это было бы здорово!

вс, 10 мар. 2019 г. в 10:20, zpalmtree <notifications@github.com>:

**Comment by SoreGums** [comment]
think they are saying "no captcha"?

so you can do that - however, it'll be emptied instantly.

>

**Comment by wolfimen** [comment]
Значит, вы считаете это не актуальным? Финансирование бесплатной раздачи черепах за капчу, я беру на себя. Можно ли внедрить оплату для пользователей черепахами, в код какого-нибудь крана?
Я нашёл несколько бесплатных архивов с кранами, но не знаю как добавить туда черепах.

**Comment by SoreGums** [comment]
It's difficult to understand what you're asking.

You can make any faucet you want. If you make it without a captcha then people would just empty the faucet balance fast

**Comment by wolfimen** [comment]
я знаю, уже есть опыт. Моя проблема в другом, я не знаю как проводить оплату trtl участникам крана. У меня был кран doge, но он был привязан к Api fauset hub, поэтому оплата шла через их сайт. Как я могу сделать переадресацию пользователей, на шлюз, к которому подключён мой электронный кошелёк? Вот начало моего сайта (http://wolfimen.beget.tech). Я его делаю не столько ради заработка, сколько для привлечения пользователей и дабы дать им возможность получить первых черепах.

**Comment by SoreGums** [comment]
Ok

To send coins from your wallet to other people from a faucet website all you need to do is collect a valid turtlecoin address from the people. Then your website backend uses the turtle-service API to send coins to the address they sent you.

Here are the API docs: https://api-docs.turtlecoin.lol/#wallet-rpc-api

**Comment by wolfimen** [comment]
Благодарю вас дружище! Пойду постигать))) Надеюсь всё получится, буду держать вас в курсе.

**Comment by wolfimen** [comment]
К сожалению я ваСче не программист и всё, что описано в вашей ссылке для меня тёмный лес. Мой максимум - это сайт и вставка скрипта или виджета. Поэтому буду думать как это сделать. Спасибо за уделённое время!

**Comment by wolfimen** [comment]
Пойду майнить, хоть децентрализацию поддержу. Видимо для остального я слишком глуп и не программист

**Comment by wolfimen** [comment]
> Вот документы API: [https://api-docs.водолазка.LoL / # wallet-RPC-api](https://api-docs.turtlecoin.lol/#wallet-rpc-api)

Приветствую! Может кто-то объяснить, как установить и настроить этот кошелёк?

**Comment by SoreGums** [comment]
> > Вот документы API: [https://api-docs.водолазка.LoL / # wallet-RPC-api](https://api-docs.turtlecoin.lol/#wallet-rpc-api)
> 
> Приветствую! Может кто-то объяснить, как установить и настроить этот кошелёк?

it is the turtle-service.exe on windows
![image](https://user-images.githubusercontent.com/317/54660019-5737bb00-4b39-11e9-9388-ee9b5faeae2c.png)

or turtle-service on linux
![image](https://user-images.githubusercontent.com/317/54660039-76364d00-4b39-11e9-84a2-86f5af3a661d.png)

and yes to do this faucet site there is not an existing copy/paste solution and will require you to program/code it.

**Comment by SoreGums** [comment]
ffs got that wrong - so use wallet-api - that is the current thing that should be the same as the documentation you linked...

**Comment by wolfimen** [comment]
Приветствую вас, уважаемый друг! Попробую разобраться в документации. Я нашёл кран в репозитории - https://github.com/krruzic/TurtleFaucet Может он объяснит? В любом случае, благодарю вас дружище, вы помогли своей отзывчивостью!

**Comment by SoreGums** [comment]
That code will not work with the current version of TurtleCoin.

**Comment by wolfimen** [comment]
Жаль... Будем думать!)))

чт, 21 мар. 2019 г. в 12:24, Nicholas Orr <notifications@github.com>:

**Comment by fexra** [comment]
Have a look at this @wolfimen https://github.com/brandonlehmann/turtle-faucet
