### ISSUE TITLE
How To Mine TurtleCoin on Windows

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#14]
# Welcome to TurtleCoin! 
###  First, let's install Turtlecoin, you can skip this if you've already done it!

1. Download this latest release of TurtleCoin. https://github.com/turtlecoin/turtlecoin/releases/download/v0.2.2/TurtleCoin-v0.2.2-windows.zip

2. Make a folder called **TurtleCoin** on your Desktop, and unzip the TurtleCoin-v0.2.2-windows.zip file into the new folder.

3. In the TurtleCoin folder on your desktop, double click the `TurtleCoind.exe` file to start syncing your blockchain. Don't worry if you don't know what that means, but it lets our wallet talk to the network, so leave it running!

4. You should be syncing and seeing yellow and white text. When you see green text, you are done syncing, it should only take 10-15 minutes. 

5. run `simplewallet.exe`. If you see an error that says you can't connect to daemon, that means you closed the `TurtleCoind.exe` window, or it means you're not done syncing. 

6. To make a new wallet, press [G] for **Generate Wallet**, and give your wallet a name and password. 

7. You're done! Copy your **spend key** and **view key** and email them to yourself so that you can restore your wallet if it breaks or if you lose it!!!

8. Go to http://chat.turtlecoin.lol and post your wallet address in #wallets and we will get you started with some TRTL to kick the tires a little bit :)
  
### Skip to here if you've already made a wallet and sync'd your blockchain

1. Download XMR-Stak Unified Miner - This will auto-detect your hardware, and tune everything for you.https://github.com/fireice-uk/xmr-stak/releases/download/v2.2.0/xmr-stak-win64.zip

2. Make a folder called **TurtleCoin Miner** on your desktop and unzip the file you just downloaded for XMR stak in there.

3. Double-click on `xmr-stak.exe`

4. Click yes when it asks if you want to run as Administrator. This is so that the program can see what hardware you're running.

5. When it asks if you want to mine Monero or Aeon, choose **MONERO**

6. When it asks which pool, put one or all of the following, if you want to use multiple pools (multiple pools is a good idea for if the one you're mining on goes down)

turtlepool.space:3333
us.turtlepool.space:3333
turtlecoinpool.ddns.net:2222

7. When it asks for "Username" just type in your TRTL wallet address. If you don't want to sync a blockchain and make your wallet later, you can make a paper wallet here http://turtlecoin.lol/wallet

8. Password is x

9. TLS is fine to say **No** in most cases

10. Do you want to use NiceHash? **No**

11. Do you want to use multiple pools? **Yes** 
Add all of the pools in the list from step 6, and give them all a weight of 10.

12. DONE!! The miner will now start scanning your hardware and will begin mining. 

We will help you!! - http://chat.turtlecoin.lol

**Comment by brandonlehmann** [comment]
This was replaced by https://docs.turtlecoin.lol/guides/mining/mining/ and thus i believe this can be closed?
