### ISSUE TITLE
Майнер для смартфона

### ISSUE THREAD

**Issue by wolfimen** [turtlecoin/meta#140]
Greetings dear community, in the face of trusted developers!
I have an idea, it would be good for decentralization to make a miner for smartphones. It is unlikely to earn a lot, but every member of our community has a smartphone. And just by turning on the smartphone miner, the user increases the decentralization of the network. Our community is growing, so I think this approach will appeal to people and attract new members to the community. 
I am unfortunately not a developer, so I can offer myself as a graphic designer miner (a little indulge in photoshop and draw). 
Waiting for your suggestions!

**Comment by SoreGums** [comment]
there is a guide in the wiki for this

https://github.com/turtlecoin/turtlecoin/wiki/Mining-with-Phone

so not sure there is anything to do here.
