### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by Poilaucul** [turtlecoin/meta#17]
Hello,

Is a faucet available?

**Comment by Watt3r** [comment]
Currently there is no faucet, I'm working on one now

**Comment by sslp** [comment]
https://faucet.trtl.me/

**Comment by RocksteadyTC** [comment]
@Poilaucul  just pinging you to make sure you see @sslp's reponse. Thanks @sslp !

**Comment by RocksteadyTC** [comment]
I've got to stop hitting close by mistake.

**Comment by polar-it** [comment]
https://turtlecoin-faucet.xhub.cloud

Based on krruzic/TurtleFaucet with some system improvement

**Comment by RocksteadyTC** [comment]
@polar-it please PR this to https://github.com/turtlecoin/turtleturtle.org
