### ISSUE TITLE
News Section on Website

### ISSUE THREAD

**Issue by GT3000** [turtlecoin/meta#18]
We should have a section for News on the website to detail new events/updates/etc.

**Comment by RocksteadyTC** [comment]
I like this idea. Where do you propose putting it?

**Comment by GT3000** [comment]
Between Specs and Roadmap I would think.

**Comment by gigantomachia** [comment]
This is my bread and butter. When the time comes to launch a News section, let me know and I can help write/draft/edit, etc.

**Comment by ar-x** [comment]
How would this be different from Medium?

Is there a desire to have our own GH based blogging system? – so that content and collaboration happens via PRs (i.e. more inclusive)? If this is considered important for the community, then I could further discuss and implement it.

cc @SoreGums

**Comment by SoreGums** [comment]
checkout #84

There is a lot to be gained by using Medium.
There is a lot to be gained by using GitHub.

how about both are done?

publish to github.
shows up on the website.
then publish to medium using their API and rel="canonical".

**issues**

writers got to create a GitHub account and use GitHub. to the people already here "what's the big deal?", well actually it's kind of a big deal, this deal gets a lot smaller with a simple guide though :)

got to create a workflow to get from GitHub to medium, probably take a weekend of dedicated effort.  
- author needs a medium account
- oAuth needs to happen in the TurtleCoin to Medium publishing script/app for both Medium & GitHub
- Need to setup the Medium Publication over at medium #84
- Need a directory added to the turtlecoin-wiki repo (probably need to rename this to turtlecoin-docs #91)
- Need to define a standard structure for articles, like the meta data part, post image, title, doc name, do the articles go in subdirectories by date to keep things organised or just have a single images folder and ... needs to be figured out.
- how about guidelines on what's acceptable or not, imagine this would be fairly liberal, ad long as it is on topic, should be fine. still probably best to define some boundaries though. commonsense not so common etc.
- finally document all that and write a guide to get people over the bump from "I have idea" to "woohoo, I wrote a thing and everyone can read it"

**Comment by ar-x** [comment]
@SoreGums 😲 I was thinking that we keep it simple so that it remains doable :) to be honest. 

I was thinking this:

1. Create one standard Jekyll repo - which contains both 1) the article sources - blog posts (news, announcements - ephemeral type of content - probably localized too) and 2) the site presentation itself.

2. Use Jekyll's conventions for _everything_. There is also a [Jekyll addon]((https://github.com/aarongustafson/jekyll-crosspost-to-medium)) to auto cross to medium. We get a lot by doing this.

3. Custom kick-ass theme.

I agree on your points on making this very approachable.

**Comment by RocksteadyTC** [comment]
I'm 50/50 on whether I should interject at all, but I have a preference for writing on Medium, and am currently the only one who writes articles. I'd prefer if the site got the data from Medium rather than writing articles in md on GitHub.

**Comment by ar-x** [comment]
@RocksteadyTC ah ok, I misunderstood the main intent. I was thinking that we would want others to contribute content via PRs. If thats not an issue, then its probably ok for now I suppose.

**Comment by RocksteadyTC** [comment]
Would it be effective to have a section that lists the last 5 articles w/ snippet lines from our Medium? That gets news and articles on the main site in a contextually relevant way, and doesn't require much work to get it done.

**Comment by SoreGums** [comment]
I'm all for simple :)

medium publication seems like the simplest then, set that up and call it a day. #84

can access medium content via APIs

**Comment by akshayrawat** [comment]
@SoreGums Yep, agreed. Just setting up a Medium publication seems the simplest thing. It would nice to close a meta issue once a while ;)


> can access medium content via APIs

hmm .. did I miss a use-case for this?

**Comment by akshayrawat** [comment]
The original issue was

> We should have a section for News on the website to detail new events/updates/etc.

Is the idea the dev blog - blog.turtlecoin.lol would include these as well?

**Comment by akshayrawat** [comment]
> Would it be effective to have a section that lists the last 5 articles w/ snippet lines from our Medium? That gets news and articles on the main site in a contextually relevant way, and doesn't require much work to get it done.

Yep, this would be nice to have on the website, doable via the Medium APIs like soregums said. And probably also add a link to the main nav to the blog (as mentioned previously).

**Comment by brandonlehmann** [comment]
Is this a RSS feed of sorts for the blog?

**Comment by brandonlehmann** [comment]
Please re-open if required.
