### ISSUE TITLE
Mobile Apps

### ISSUE THREAD

**Issue by DaveDays2** [turtlecoin/meta#19]
Android and iOS apps could go a long way towards marketing and adoption. 

Xamarin could be used for a write once deploy to all solution. The app could also show stats such as global hash rate, total circulating turtles, and eventually market price when applicable. 

I believe a wallet-less app could be created within a week and a fully functional version after that.

**Comment by editfmah** [comment]
At this precise moment, Apple will not approve any apps referencing a cryptocurrency that is not approved.  I'm still waiting for Aeon almost 8 months later.

**Comment by editfmah** [comment]
And that is even if there is no crypto, and the app just interacts with a node.

**Comment by DaveDays2** [comment]
ARK recently got their wallet on iOS. But even in the case that we can't release to iOS an android app would still be cool.

**Comment by editfmah** [comment]
It would, it was more FYI.

**Comment by DaveDays2** [comment]
OK after checking it out it looks like ARK got on iOS in kind of roundabout way:

ARK iOS Mobile Wallet : 
1. Install ‘Ionic View — Test Ionic Apps’ https://itunes.apple.com/us/app/ionic-view-test-ionic-apps/id1271789931?mt=8
2. Open and click the eye at the bottom
3. Enter the ID 0894ffa2 and “View App”

**Comment by editfmah** [comment]
Oh, that's dirty.  That is so getting banned or pulled soon as it totally breaks the enterprise signing agreement.

**Comment by DaveDays2** [comment]
Not sure where I should post this, but I can't apply labels. Apparently somebody needs to grant permission.

**Comment by DaveDays2** [comment]
@editfmah Yeah, it's totally going to get pulled. Looks like no iOS for now. Maybe instead of Xamarin a native Android project is the way to go then.

**Comment by krruzic** [comment]
Why not xamarin though? Might as well have a codebase for iOS if ever possible.

**Comment by CaptainMeatloaf** [comment]
I agree that xamarin is a good choice, it allows things to be cross-platform - there's no point restricting yourself to one platform from the start when you can have the flexibility to expand to many in the future if needs be.

**Comment by DaveDays2** [comment]
I find Android Studio is generally cleaner and faster to develop with than Xamarin, and at least for now it won't be able to get on the iOS store anyways. I guess that could change in the future, also Xamarin allows building to windows store as far as I know. One risk of Xamarin is since it's owned by Microsoft continued support isn't guaranteed. 

I'm happy either way, I just really want to see a Turtle app!

**Comment by CaptainMeatloaf** [comment]
Indeed, with xamarin you leave yourself with the cross-platform bit open, if for example we wanted to release an xbox app, or a hololens app (don't have to, just platforms it supports), we could do so by having the same code re-used in Xamarin.

**Comment by neverdot** [comment]
Basic app prototype in Xamarin - https://imgur.com/a/2RO2c

**Comment by krruzic** [comment]
sweet dude, where's the code?

**Comment by neverdot** [comment]
I can make a repo tomorrow. Considering restarting with Android Studio first (ran into a few roadblocks with Xamarin). Mostly looking for comments on the design.

**Comment by krruzic** [comment]
Design is really good please keep it xamarin. I don't know anything about android dev but I know enough C# and xaml to help with xamarin. Signin page should fill some of that empty space somehow.
Network info should show charts like the pool sites do.

**Comment by neverdot** [comment]
Thanks for the feedback, I'll see what I can do. 

We might make a prototype in Android Studio as well just for comparison but won't commit to anything.

**Comment by holmholk** [comment]
Here is the repo for the Xamarin mobile app:
https://github.com/holmholk/TurtleCoinMobileWallet-Xamarin/tree/master

**Comment by holmholk** [comment]
@krruzic Good suggestion, I added the turtle shield image on the landing screen. What do you think? https://imgur.com/1283jud

**Comment by CaptainMeatloaf** [comment]
I'd appreciate it if some attribution was added for the code that was taken from TurtleBot.

**Comment by neverdot** [comment]
@CaptainMeatloaf Done. 

We may not be doing any more development on Xamarin since there is already a native iOS app and an Android app currently underway.

**Comment by CaptainMeatloaf** [comment]
I'm not a fan of the native android app - by creating an app specifically for it, you're restricting the possible further expansion of the app to other platforms.

Xamarin was a good choice as it left the options open for the future.

**Comment by neverdot** [comment]
@CaptainMeatloaf if you can help us get the daemon working with Xamarin we can finish that, otherwise I'll join the native Android effort. I have made progress getting things working with Android NDK but made little to no progress getting it to work with Xamarin.

**Comment by CaptainMeatloaf** [comment]
You may find this link useful: https://blog.xamarin.com/build-and-debug-c-libraries-in-xamarin-android-apps-with-visual-studio-2015/

I will not be able to help until next week, but calling and building native code is possible, especially as you can generate MSVC projects with cmake for turtlecoin.

**Comment by turtle0x1** [comment]
@neverdot @CaptainMeatloaf  Any repos available yet ?

**Comment by cameronbroe** [comment]
What about React Native for the app? The UI can be done in JavaScript and cross-platform and dropping into Swift or Java is pretty simple for anything that really needs to be native. It also would be easier for non-VS people to jump in and contribute.

**Comment by alexxv** [comment]
+1 for React Native, much more portable then xamarin, great ecosystem and lots of people can code in JavaScript

**Comment by alexxv** [comment]
All the big guys are using react native for building their mobile apps (fb, instagram, Dropbox, Airbnb)

**Comment by Zexuz** [comment]
We need a to **agree on something**.

Should we build it **cross-platform**?
In this options we have.

- Xamarin https://www.xamarin.com/
- React.Native https://facebook.github.io/react-native/
- Ionic https://ionicframework.com/

or go the route with **native code.**

Java/Kotil and swift.

**Comment by BebopTC** [comment]
There does not need to be a choice or agreement. If you are developing, you are free to develop in any tech stack and platform you want. There is nothing wrong with choice in the marketplace. 
Either contribute to an existing project with the tech it is using, or fork it and modify to your liking or start your own.

**Comment by Zexuz** [comment]
That is correct.

But devs like myself that only have a couple of hours to spare can't go and create a new app from scratch. 
Our services is in contributing. But if there is noting to contribute? Or even worse, what if there is 3 different project. None have a working product but they all are aiming to do the same thing?

I will start working /looking at the Kotlin app since it is under the turlecoin account. 

But i really think this community will benefit from having a official app that we all can work together.

**Comment by BebopTC** [comment]
> But devs like myself that only have a couple of hours to spare can't go and create a new app from scratch.
I understand and appreciate that and fit into the same boat. That is why those who are doing the work make the call. It is a doer's market, so to speak. Those who can only marginally contribute should not dictate and impose choices on those who are able to put in more work. If you want to dictate those kinds of choices, start a project and ask others to contribute and collab with you. It is not uncommon for project founders/leaders to only manage from 30,00 ft. while other contributors write the bulk of code.

"Official" app is a separate issue.

**Comment by BebopTC** [comment]
BTW @Zexuz i am not trying to give you a hard time. You are free to discuss and collab with everyone and if a group agrees to a platform, tech, or any decision that is all fine and good. In fact it's great. I just want to emphasize to the community at large that EVERYONE is free to contribute any way he or she wants, and if the existing projects don't suit them it is entirely fine and good to start another. 

Happy coding! Cowabunga

**Comment by Zexuz** [comment]
Ye, I understod that. And with the this project blowing up in less than one month I understand that is hard to keep up with everything. But a "optional" roadmap/todo list for the android-kotlin app would be much appreciated. For example. I'm not saying YOU should do it. Ofc someone with knowledge about the project/situation should do it.

As of now it's a bit of a pain and a steep curve if you want to contribute for someone that does not know the project (once again, talking about the kotlin-android app.).
