### ISSUE TITLE
Equivalent of monero's 'rescan_spent'

### ISSUE THREAD

**Issue by CaptainMeatloaf** [turtlecoin/meta#21]
I have noticed several of my larger transactions have been getting stuck.

From what I can gather, they are trying to use spent key images, so therefore we need something like Monero's `rescan_spent` feature to release them.

**Comment by RocksteadyTC** [comment]
In the mean time, @CaptainMeatloaf I'd suggest breaking up your future transactions into 100k increments and sending via 0 mixin.

**Comment by brandonlehmann** [comment]
Isn't this handled in `reset` ?

**Comment by SoreGums** [comment]
either way, this is probably fixed now in zedwallet
