### ISSUE TITLE
Turtle-pool UI enhancement 

### ISSUE THREAD

**Issue by DaveDays2** [turtlecoin/meta#23]
Some users are having trouble noticing that selected pool stats (such as block found) is for that specific pool and not global. I propose adding a separator such as in this image: https://imgur.com/a/mCUd5

I would have posted this in the turtle-pool issues but I don't have permissions to add issues there.

**Comment by CaptainMeatloaf** [comment]
I knocked this together for http://turtlepool.space
![image](https://user-images.githubusercontent.com/3893247/34921374-2f6892c4-f979-11e7-9200-6047ec2b978e.png)
But nobody seemed bothered in discord - if people like this they can react on here, otherwise I'll drop the split/redesign

**Comment by brandonlehmann** [comment]
Is this still an issue?
