### ISSUE TITLE
Resetting does not appear to reset from the start

### ISSUE THREAD

**Issue by CaptainMeatloaf** [turtlecoin/meta#24]
When you type reset into simplewallet, sometimes it happens that the wallet is not reset correctly, and only seems to reset from around when you last opened the daemon.

From what can be gleaned, it appears that the bug is related to the daemon re-orgs, as simplewallet appears to request the reset correctly.

More information in this screenshot from discord, where the problem was diagnosed:
![image](https://user-images.githubusercontent.com/3893247/34970289-7e734cd6-fa6b-11e7-932c-d9e58174f6ad.png)

**Comment by ZedPea** [comment]
Assuming this is the same issue as the balance going to zero issue, it's pretty high priority in my opinion - It's probably the number one issue that new users face, and whilst there are quite a few fixes for it they all seem to be temperamental and sometimes you have to try a lot of times before the balance will come back - very frustrating.

**Comment by brandonlehmann** [comment]
Haven't seen this in a while... handled via the re-write me thinks.
