### ISSUE TITLE
Calculating Turtle Supply

### ISSUE THREAD

**Issue by neverdot** [turtlecoin/meta#25]
I saw a few questions about turtle supply and tail emission so I decided to explore the Turtle supply over time. It doesn't seem possible to get exact numbers but I believe I've come up with a reasonable estimate. 

Turtle supply over the next year:
https://i.imgur.com/K8m6n5U.png
[Google Sheet](https://docs.google.com/spreadsheets/d/1-p9Deu37eg-PQaNCd_IqNZMg_HW5hUV66fdFw-DJdYM/edit?usp=sharing)

Turtle supply over the next 100 years:
https://i.imgur.com/R0980HU.png
[Google Sheet](https://docs.google.com/spreadsheets/d/1XPoVACehjGkJSIZzbA02yaslS_vtU9j7jxDzeyibdzc/edit?usp=sharing)

To generate the data I used the base reward formula
 `uint64_t baseReward = (m_moneySupply - alreadyGeneratedCoins) >> m_emissionSpeedFactor;` 
from [the Turtle repo](https://github.com/turtlecoin/turtlecoin/blob/a7c267f3ca32624017a634d11b8513d82701832d/src/CryptoNoteCore/Currency.cpp) and created a simple generate method in C# based on 30 second blocks. 

    DateTime StartDate = new DateTime(2017, 12, 10);

    const int blocksInADay = 2 * 60 * 24; // 30 sec blocks so = 2 blocks per min, 60 mins per hour, 24 hours per day

    const long maxBlocks = 2000000; // ~110 years is 100000000, ~1 year is 2000000

    const string delim = ", ";
    const string delimDate = "-";
    const string term = "\n";

    long moneySupply = 1000000000000;
    long alreadyGeneratedCoins = 0;
    int emissionSpeedFactor = 25;

    public string Generate()
    {
        DateTime dateTime = StartDate;
        long currentBlock = 0;
        string result = "";
        string date;

        while (alreadyGeneratedCoins < moneySupply && currentBlock < maxBlocks)
        {
            long blockReward = (moneySupply - alreadyGeneratedCoins) >> emissionSpeedFactor;
            alreadyGeneratedCoins += blockReward;
            date = String.Join(delimDate, dateTime.Year, dateTime.Month, dateTime.Day);
            result += String.Join(delim, currentBlock, Math.Round(alreadyGeneratedCoins / 1000000000.0f, 2), blockReward, date, term);
            currentBlock++;
            dateTime.AddSeconds(30);

            // skip ahead 1 day
            for (int i = 0; i < blocksInADay - 1; i++)
            {
                blockReward = (moneySupply - alreadyGeneratedCoins) >> emissionSpeedFactor;
                alreadyGeneratedCoins += blockReward;
                dateTime = dateTime.AddSeconds(30);
                currentBlock++;
            }
        }
        return result;
    }

Let me know if you find any errors and I'll update my charts.

**Comment by RocksteadyTC** [comment]
wow this is good work. The curve looks about right, but I did not double check the numbers. long_m_moneysupply looks funny though. is that atomic units or what?

**Comment by neverdot** [comment]
I just copied the names from the c++ files in the turtle source, I'll change them to follow C# convention.

**Comment by bx549** [comment]
I was fiddling around with the TurtleCoin block reward schedule and I got (basically) the same results as @neverdot . This is assuming a new block every 30 seconds on average and also not considering the penalty for large blocks (that I am still trying to understand).  My implementation is in R. The simulation goes out approximately 100 years into the future. As of today, June 11, 2018, the actual block reward is right on track with the schedule.

[TurtleCoin.pdf](https://github.com/turtlecoin/meta/files/2091460/TurtleCoin.pdf)


In general I am interested in the economic trade-offs between block size and block frequency in a cryptocurrency protocol.  I will make a separate post on this topic since it encompasses more than just the block reward and circulating supply of coins.

**Comment by brandonlehmann** [comment]
https://turtlecoin.supply/ replaces this, yes?

**Comment by brandonlehmann** [comment]
Better yet: https://explorer.turtlecoin.lol/supply.html
