### ISSUE TITLE
Creation of a sub Discord channel for currated and organized promotion efforts

### ISSUE THREAD

**Issue by iwoojoo** [turtlecoin/meta#29]
I would suggest a new subchannel that allows for the Discord users to easily access a currated list of current efforts that profit from individual contributions such as 
- Voting forms
- Exchange listing forms
- promotion campaings

As such this channel would be where information is readily gathered to allow the user to hit the ground running.
Such Subchannel would be best organized best in 2 parts
one part for Currated listings(moderated and no chat)
and another for discussion to gather focus on topics
this all would probably be best grouped together with memes as such also further promote TRTL.

**Comment by brandonlehmann** [comment]
Huh? Can this be closed?

**Comment by SoreGums** [comment]
it can be re-opened if needed
