### ISSUE TITLE
URL is 'meta.turtlecoin.lol'

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#3]
I believe it is important to have a clear and memorable URL to give to others for them to reach this board. meta.turtlecoin.lol is the one I chose, but it does not have to be the only one if something else fits better, like forum.turtlecoin.lol

**Comment by GT3000** [comment]
suggestions.turtlecoin.lol could work, workshop.turtlecoin.lol or lab.turtlecoin.lol

Those are just some ideas.

**Comment by brandonlehmann** [comment]
This exists. Please close.
