### ISSUE TITLE
Wrong color code in Brand Guidlines

### ISSUE THREAD

**Issue by holmholk** [turtlecoin/meta#30]
I was checking the Brand Guidlines here:
https://github.com/rcdmar/turtlecoin.lol/blob/master/brand/TurtleCoin_Brand_Book_2018.pdf

The hex code for the green primary color only has five digits #0843d. It should be #00843d I believe.

**Comment by RocksteadyTC** [comment]
This is correct, I'll let Adjoining know. Thank you @holmholk
