### ISSUE TITLE
How to mine turtle referencing old wallet

### ISSUE THREAD

**Issue by neverdot** [turtlecoin/meta#31]
We need to update the mining guide, https://github.com/turtlecoin/turtlecoin/wiki/How-To-Mine-TurtleCoin-on-Windows References v0.2.2 instaed of latest (0.3.0)

**Comment by RocksteadyTC** [comment]
Fixed

**Comment by brandonlehmann** [comment]
Fixed in latest documents at https://docs.turtlecoin.lol/guides/mining/mining/ 

This can close
