### ISSUE TITLE
Windows10: Test for real tty and prompt to use winpty

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/meta#32]
OS: Windows10
Version: 0.3.0

I use git for windows git-bash cli rather than cmd.exe

as such it is not a real tty and causes issues, like:

- not handling the password prompting in simplewallet.
- not updating the screen properly in TurtleCoind

once i figured this out all was well, I get colours now and passwords are hidden and prompted for.

easy to test, install git for windows, open git-bash, run the programs and notice things aren;t quite right.

```
$> ./TurtleCoind.exe
```

now run the programs with winpty and everything is how it should be

```
$> winpty ./TurtleCoind.exe
```
[Imgur image to show the diff](https://i.imgur.com/NDASFjI.png)

ref: https://github.com/docker/toolbox/issues/136

**Comment by RocksteadyTC** [comment]
nice!

**Comment by brandonlehmann** [comment]
@SoreGums do we still need this?
