### ISSUE TITLE
URI Scheme

### ISSUE THREAD

**Issue by krruzic** [turtlecoin/meta#33]
Has something like this been decided? BIP21 decided
`bitcoin:<address>[?amount=<amount>][&label=<label>][&message=<message>]` 
for bitcoin and I think something similar would work
`bitcoin:<address>[?amount=<amount>][&payment_id=<paymentid>]`

**Comment by cameronbroe** [comment]
Any reason we'd keep `bitcoin` as the scheme? I'd say switch the scheme to `turtlecoin` so there would be no collisions on user's systems when they have a BitCoin wallet installed as well.

**Comment by fexra** [comment]
In the [Turtlecoin WooCommerce Gateway](https://github.com/turtlecoin/woo-turtle) plugin I have done the following:

`$uri = "turtlecoin:$address?amount=$amount?payment_id=$payment_id";
`

**Comment by RocksteadyTC** [comment]
the turtlecoin URI has been active since v0.1.1 iirc

**Comment by brandonlehmann** [comment]
Let's close this then?
