### ISSUE TITLE
Create Discord Channel for Speculation and Mining

### ISSUE THREAD

**Issue by fexra** [turtlecoin/meta#34]
Currently there is too much price speculation and mining going on in the general chat rooms. This creates massive amounts of FUD and is not a nice atmosphere for new people, and well everyone really. Therefore, I propose that we create two new discord channels: one for price speculation and one for the discussion about mining. 

Thoughts?

**Comment by DmontyFont** [comment]
How about take this acticity to a different app all together like Telegram or something.

**Comment by fexra** [comment]
@DmontyFont That is not a bad idea. I think for mining we already have #pools so that may not be necessary, but it would be nice to separate speculation from effort and the community. Some speculation is healthy, but we don't want the discord channels to be over run with people that are only there for self interest.

I made a telegram channel for speculation. Let's see how it goes :)

https://t.me/TRTLprice

**Comment by RocksteadyTC** [comment]
@fexra #pools is not a public channel. It is not a place for miners to seek help. All help requests go to #help so they aren't further separated from those who may help them.

**Comment by RocksteadyTC** [comment]
Anything that takes speculation of out general is a welcome change, however I'd discourage any labeling or implying that it is in any way an official communications channel.

**Comment by derp-derp-derp** [comment]
This can probably be closed since there's #mining in Discord now, and #market-talk got whacked. Agreed?
