### ISSUE TITLE
[BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/meta#35]
running simplewallet and leaving it open eventually results in continuous messages like this

> [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error

<img src="https://imgur.com/HFZeZHe.png" width="200px" />

[screenshot^^](https://imgur.com/HFZeZHe)

wasn't sure if I should report this or not...

I have TurtleCoind running as well - restarting both the daemon and wallet gets rid of the message for a while, then it comes back again.

windows 10
TurtleCoin v2.1.2.1251 (0.1-g5be60bf) > Module folder: I:/TurtleCoin-v0.3.0-windows-CLI/TurtleCoind.exe
TurtleCoin wallet v2.1.2.1251 (0.1-g5be60bf)

**Comment by llawwehttam** [comment]
I can also reproduce this issue on Ubuntu 17.10

**Comment by RocksteadyTC** [comment]
This is a result of the daemon segfaulting in the background, and when the simplewallet can no longer read it, it will give this error.

**Comment by brandonlehmann** [comment]
Please update to the latest release @SoreGums
