### ISSUE TITLE
Static linux binaries are not totally static

### ISSUE THREAD

**Issue by kernel-sanders** [turtlecoin/meta#36]
As of v0.3.0

The "static" linux binaries you have on the github release page are statically compiled against libbost but not glibc. This causes issues on machines with older glibc libraries, which include the most up to date CentOS 7. Perhaps the build pipeline could be changed to statically compile against glibc as well (will probably double the binary size).

Regular linux TurtleCoind:

```bash
$ ldd TurtleCoind
./TurtleCoind: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./TurtleCoind)
        linux-vdso.so.1 =>  (0x00007ffc8dfda000)
        libboost_system.so.1.58.0 => not found
        libboost_filesystem.so.1.58.0 => not found
        libboost_program_options.so.1.58.0 => not found
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f61d850b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f61d8302000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f61d7ffa000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f61d7cf8000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f61d7ae1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f61d771e000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a96f18c000)
```

"static" TurtleCoind

```bash
$ ldd TurtleCoind
./TurtleCoind: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./TurtleCoind)
        linux-vdso.so.1 =>  (0x00007ffceebee000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd95adf7000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fd95abef000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd95a8e6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd95a5e4000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd95a3ce000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd95a00a000)
        /lib64/ld-linux-x86-64.so.2 (0x000055b2ac8f9000)
```

**Comment by John2309** [comment]
We have the same issue

[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ ./TurtleCoind 
./TurtleCoind: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./TurtleCoind)
[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ ldd TurtleCoind 
./TurtleCoind: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./TurtleCoind)
./TurtleCoind: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./TurtleCoind)
        linux-vdso.so.1 =>  (0x00007fff2a1a8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f64a3468000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f64a3260000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f64a2fd8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f64a2c40000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f64a3698000)
[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ 

If we compile GLIBC-2.15 from source into /opt and link the libraries we get a segmentation fault

[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ export LD_LIBRARY_PATH=/opt/glibc-2.15/lib:$LD_LIBRARY_PATH
[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ ./TurtleCoind 
Segmentation fault
[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$ ldd TurtleCoind 
        linux-vdso.so.1 =>  (0x00007fffe0200000)
        libpthread.so.0 => /opt/glibc-2.15/lib/libpthread.so.0 (0x00007ffbef968000)
        librt.so.1 => /opt/glibc-2.15/lib/librt.so.1 (0x00007ffbef748000)
        libm.so.6 => /opt/glibc-2.15/lib/libm.so.6 (0x00007ffbef450000)
        libc.so.6 => /opt/glibc-2.15/lib/libc.so.6 (0x00007ffbef0a8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffbefb88000)
[john@server TurtleCoin-v0.3.1-linux-staticboost-CLI]$

**Comment by nnamon** [comment]
Only libboost is compiled in statically right now as implied by the filename.

Please compile from the release source instead.

**Comment by brandonlehmann** [comment]
This has been handled.
