### ISSUE TITLE
Provide a minimal make target

### ISSUE THREAD

**Issue by paulie-g** [turtlecoin/meta#42]
Providing an option to skip targets that are unnecessary for a user who just wants to sync the blockchain and create a wallet wouldn't go amiss, something like make release-minimal. It's obviously difficult to keep up with all this stuff for a small project, so reducing the surface area for potential breakage might be helpful.

This is in reference to issue: #41

**Comment by paulie-g** [comment]
Opened an issue in turtlecoin/turtlecoin#29

**Comment by brandonlehmann** [comment]
This has been handled. you can build single make targets
