### ISSUE TITLE
Remove solo miner from main download

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/meta#45]
Basically, a lot of users will have missed the link on how to start mining, and will wonder how to use the solo miner (you have to specify an --address in the cli which most users are unaware of), or will wonder why they get no output (you have to have turtlecoind running).

Even if they do get it working, they're very unlikely to find a block, with the hashrate how it is, and the miner being CPU only. It also can't be used with a big GPU rig user who might be interested in solo mining, as it doesn't support GPU's.

It seems it would be a better idea to just not include a miner, and then they will hopefully find the http://mining.turtlecoin.lol link, and get started off on the right track instead.

**Comment by adigupta13** [comment]
or maybe provide a readme for the miner in the download folder stating the correct and use and the link to other miners for GPU usage etc

**Comment by AvanteVandaleur** [comment]
For new forks of Turtlecoin, solominer would still be important.  Where can one enable some kind of logging info when solominer starts/stops/finds block... so that miners know they are in fact connected and not just blank screen? thanks  -AV

**Comment by brandonlehmann** [comment]
```
  -h [ --help ]                       Produce this help message and exit
  --version                           Print the version number and exit
  --address arg                       Valid cryptonote miner's address
  --daemon-host arg (=127.0.0.1)      Daemon host
  --daemon-rpc-port arg (=11898)      Daemon's RPC port
  --daemon-address arg                Daemon host:port. If you use this option
                                      you must not use --daemon-host and
                                      --daemon-port options
  --threads arg (=32)                 Mining threads count. Must not be greater
                                      than you concurrency level. Default value
                                      is your hardware concurrency level
  --scan-time arg (=30)               Blockchain polling interval (seconds).
                                      How often miner will check blockchain for
                                      updates
  --log-level arg (=1)                Log level. Must be 0..5
  --limit arg (=0)                    Mine exact quantity of blocks. 0 means no
                                      limit
  --first-block-timestamp arg (=0)    Set timestamp to the first mined block. 0
                                      means leave timestamp unchanged
  --block-timestamp-interval arg (=0) Timestamp step for each subsequent block.
                                      May be set only if --first-block-timestam
                                      p has been set. If not set blocks'
                                      timestamps remain unchanged
```

I'd start with ```--log-level 5``` for maximum detail on how the miner is working.

**Comment by AvanteVandaleur** [comment]
That should suffice for the interim. Excellent. Thank you. -AV

**Comment by AvanteVandaleur** [comment]
aha! default log level. many thanks!!  -AV
