### ISSUE TITLE
Print both private keys on generation

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/meta#48]
Currently, when you create a wallet you'll get an output something like this:

```
2018-Feb-06 01:43:33.584519 INFO    Generated new wallet: TRTLv2JjBVQjQ7ecQ699e4NhR2uddNfNBCe34jHsCNH1gagooGSGYWE9vYxRLLzWgHJ6cU6DUE9sWWz9hERe8MpJfBVjhDRzTwy
2018-Feb-06 01:43:33.584519 INFO    view key: c6863b261ac8778244e3dcb74465ab978a843bd249325fb986d272569c270101
```

Should we not print out the spend key as well, rather than requiring the user to know to type `export_keys`?

I'm aware printing the view key is disabled in the new build because of the logging issue, so that would need to be addressed before implementing this.

It looks like we'd just need to add `"spend key: " << Common::podToHex(keys.spendSecretKey);` to https://github.com/turtlecoin/turtlecoin/blob/master/src/SimpleWallet/SimpleWallet.cpp#L790

**Comment by RocksteadyTC** [comment]
I like this idea.

**Comment by wbills** [comment]
https://github.com/turtlecoin/turtlecoin/pull/42

**Comment by ereptor81** [comment]
https://github.com/turtlecoin/turtlecoin/pull/42
