### ISSUE TITLE
Do you want TurtleCoin listed on Bisq Decentralized Exchange?

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#49]
We have an opportunity to code an integration for a decentralized Exchange called Bisq. https://bisq.network

We get one shot at submitting this, and if we fail review, we do not get a second chance. It's not a hard integration by any means, but before diverting our attention from anything else, I'd like to know if the community wants this integration. It needs to get the full attention it deserves to not waste this other developer's time reviewing it. 

**This is not a thread to talk about your favorite exchange, or the last one that rained you free coins on Reddit, it's a yes or no question, and if you say no, we'd like to hear a supporting argument so we can make a well-informed decision.**

Thank you for your participation, we look forward to your responses. 

For developers: Like we said, it's not a difficult process to do what this developer is asking, but the developer specifies that if the application fails to pass review, there is no second chance. We'd like to check over this entire application 5 times if we have time, just so that we know we're giving our 110% best effort to making this happen successfully. 
Here are the details of the process.
https://github.com/bisq-network/docs/blob/master/exchange/howto/list-token.adoc

**Comment by GT3000** [comment]
Yes.

**Comment by dh47** [comment]
Yes please.

**Comment by cupcakeBullet** [comment]
Yes :)

**Comment by ac1984** [comment]
Are there any downsides? (except for the one-time dev effort)

**Comment by RocksteadyTC** [comment]
@ac1984 this is what I'm soliciting here

**Comment by RocksteadyTC** [comment]
@ac1984 I'd like to hear from others who know of any downsides so we can be better informed before investing the time. A potential downside for me, personally, would be an integration that languishes with low volume.

**Comment by karaigumon** [comment]
yes

**Comment by HoseA-mang** [comment]
Yes

**Comment by IgnacioLPM** [comment]
Yes

**Comment by akshayrawat** [comment]
@ac1984 Does the integration have an ongoing cost (dev effort, our resources etc)?

**Comment by akshayrawat** [comment]
@ac1984 @RocksteadyTC  Does the integration have an ongoing cost (dev effort, our resources etc)?

**Comment by jonathanjm** [comment]
Yes!

**Comment by RocksteadyTC** [comment]
@akshayrawat No that I'm aware of, no. Maybe if we drastically changed our communication interface somehow. I could be missing something, but I think it's just the time cost.

**Comment by sslp** [comment]
Yes

**Comment by RocksteadyTC** [comment]
Ideally, I'd like to have as many qualified eyes on the branch before it becomes a PR

**Comment by rcdmar** [comment]
I'm gonna say no just to combo break. (But really **yes**)

**Comment by bd-ongithub** [comment]
Exchange feels like a ghost town, the volume is abysmal.
That said, however, expanding TRTL availability into another exchange is still an option to consider. Volume wise, judging from TradeOgre I think we bring our own volume, and since bisq is decentralized it could alleviate some worries a few buyers have expressed with TO (sketchy, could exit scam, etc.).

So I'll go with yes :)

**Comment by RocksteadyTC** [comment]
@bd-ongithub I had a similar concern about the volume, which is why I've ruled out exchanges like binance for this quarter, despite many prompts from the community. I think a decentralized exchange hits the trust issue people have with trade ogre, and like you said, as with trade ogre, we have volume, we just need somewhere to put it.

**Comment by pixelryan** [comment]
Yes.  I was going to say No, its better to use your time on something that benefits the end users, but yeah tradeogre is pretty sketchy so you convinced me with the last comment.

**Comment by dialuplama** [comment]
Yes

**Comment by beezTEM** [comment]
Yes!

**Comment by swampfighter** [comment]
FYI - I'm old, jaded, and pragmatic.  I vote NO. 

We have tradesatoshi now. So the need for another exchange is mitigated considerably.

As for bisq, their traffic is abysmal.  Adding coins gives bisq more credibility than a coin gets by being listed on bisq.  It doesn't add to trtl's visibility or marketing in any way, as most of us had to go see wtf bisq was. 

There are other, more important tasks that Rocksteady can be working on, tasks that he'd probably enjoy working on more.

**Comment by SoreGums** [comment]
Vote no - installed the app, great idea executed well, simply has no traction.

While p2p apps sound cool, if what you want to do is not in chrome (aka a std web browser) it is pretty much doa, unless it is so awesome that everyone will use it, like BitTorrent and getting TV shows/Movies for free.

Got other things to focus on right now.
Bisq is solid, just the whole install and app to do stuff is very niche still.

**Comment by fexra** [comment]
Even though the exchange Bisq is more or less dead, I still think it would be a good investment for brand image. Bisq is a P2P, decentralized and anonymous exchange that runs on the TOR network. If we want to claim that we care about privacy, this would be an excellent opportunity to show that to everyone. I doubt it will bring much active trading, but building an integration shouldn't be too hard if we focus our efforts on it.

**Comment by CamioCross** [comment]
Yes. Bisq is slow but they have traction on Twitter and the eyes of people in the higher runs of the crypto community.

**Comment by rwdim** [comment]
It would depend on the level of effort. There's not much going on Bisq now, and pretty much all of the transacting is in Bitcoin. 

Seems to me it might be time better spent getting listed on sites like CoinMarketCap. Not only does it get you in front of people, but it enables apps to use their APIs to query the coins performance and characteristics.

**Comment by RocksteadyTC** [comment]
CoinMarketCap has volume requirements we don't meet

**Comment by brandonlehmann** [comment]
Handled here -> https://github.com/bisq-network/bisq-assets/pull/73 thanks @RocksteadyTC

**Comment by brandonlehmann** [comment]
This is out of our hands now

**Comment by RocksteadyTC** [comment]
vaya con dios
