### ISSUE TITLE
Möbius Whitepaper

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#5]
I am ear-marking time to start thinking about writing a whitepaper for the Mobius concept. I'd like to use this space to post links to inspiration and things that I found compelling about other whitepapers. I'd like to keep it as design-focused as possible, meaning, illustrate the concept, create the working model, and then let peer professionals implement best practices and production development processes.

**Comment by brandonlehmann** [comment]
Please re-open if required. There have been no updates in 7 months.
