### ISSUE TITLE
New password should be entered twice

### ISSUE THREAD

**Issue by seanspotatobusiness** [turtlecoin/meta#52]
There is a risk of mistyping a new password and being unable to re-enter a new wallet. I suggest that when making a new wallet, the password must be entered twice to ensure correct typing.

**Comment by RocksteadyTC** [comment]
I like this idea.

**Comment by SoreGums** [comment]
I think adding verify password is a solid step.
At the same time, having the keys to restore a wallet is the number 1 priority.
To achieve that have the a switch that is not specified goes through a super lame & obnoxious verify everything setup process.

Obnoxious verify process = here is you address, write it down, you got it? Great, tell me what it was, nice, here is your spend key, write it down, etc.
Verify everything.

If you specify the switch/param at startup then you get the current thing (you know what you're doing wallet will stfu & gtfootw).

**Comment by ereptor81** [comment]
https://github.com/turtlecoin/turtlecoin/pull/64

**Comment by RocksteadyTC** [comment]
@ereptor81 This has been approved

**Comment by brandonlehmann** [comment]
This has been handled, yes?
