### ISSUE TITLE
Using GUI wallet and want to upgrade to 0.3.1? Load simplewallet from .wallet.backup

### ISSUE THREAD

**Issue by js-21** [turtlecoin/meta#53]
From instructions page -
https://github.com/turtlecoin/turtlecoin/releases/tag/v0.3.1

Step 3: you'll go to open your wallet with **simplewallet,** but if you've been using GUI wallet, you need to open wallet from "WalletName.WALLET.BACKUP" instead of just the first .wallet. 

The issue I had trying to load traditional .wallet was it gave me red text saying "cannot load wallet" and thinks the password is wrong.

After using the GUI wallet, the .wallet will only open with GUI going forward, whereas the .backup will open with simplewallet.

Shout out to Ereptor for the assistance.

**Comment by brandonlehmann** [comment]
0.3.1 is kind of old, can we close this up please?
