### ISSUE TITLE
Open Project-specific Issues w/ Project Instead of here.

### ISSUE THREAD

**Issue by BebopTC** [turtlecoin/meta#54]
To help keep things organized and to make sure the right people are aware about the right issues, we should file project-specific issues (feature requests, bug reports, etc) on the Issue pages of projects' own repos instead of here. That means if you find a problem or have a request about a specific change in, for example, Turtlecoind, Simplewallet or something specific to the core software, it should be filed in the turtlecoin/turtlecoin issue tracker. Or for instance, if it's about a typo or content that needs to be added or changed in the current turtlecoin.lol website, file it in turtlecoin/turtlecoin.lol
This will ensure the developers working on those projects are notified and able to see them, and provides an issue for contributors to track against in commits/PRs. Moving forward, issues of that sort will likely be marked closed with a reply asking to refile in the appropriate place.

If you're not sure, no worries, no one is gonna get stuffed in their shells for it! Turtle's are all about fun and we're here to help each other. It'll just help us with house cleaning n organization. Keeping the turtlecoin/meta discussion as the go-to place for the concerns that are outside of the scope of a particular project - strategy, new project proposals and ideas, PR/marketing, community management, announcements - will give higher visibility into those meta issues 

Happy coding!

**Comment by brandonlehmann** [comment]
Please re-open if required.
