### ISSUE TITLE
Crashes upon start

### ISSUE THREAD

**Issue by Trijiv** [turtlecoin/meta#55]
I followed the instructions exactly but it crashes once i start mining... I use windows 10 Pro, Turtle Wallet Ver. 1.0.6609.42743, and XMR Stack Win64. When i start mining it says Error GPU 0 (Or GPU 1) and just shuts the miner down. If i try it a few times Windows 10 BLUE SCREENS and says that there is a bad pool call. How do i fix this? I want some of those sweet sweet turtle coins. :p

**Comment by ZedPea** [comment]
If it's an error about cuda, you can fix this yes.

If you are using a nvidia card, try opening nvidia.txt in the same directory as the xmr-stak.exe, and lowering the value for threads until it stops crashing. A good start would be lowering by 8 at a time.

However, xmr-stak is not developed by the turtlecoin team, so in future I would suggest coming to the #help or #mining channel in the discord - http://chat.turtlecoin.lol - or opening an issue on the xmr-stak repo - https://github.com/fireice-uk/xmr-stak

There is also an FAQ which might help you out with some other common mining/xmr-stak issues - https://github.com/turtlecoin/turtlecoin-wiki/blob/master/FAQ.md#xmr-stak-issues

Thanks!

**Comment by BebopTC** [comment]
Sounds like this is an xmr-stak related issue. You can join our discord chat [](http://discord.turtlecoin.lol) and ask for help in the #help channel, we prefer to keep issues in this repo related to meta discussion about TurtleCoin projects & community. 

That said I'll leave this issue open a while so you might get some support here. Good luck!

**Comment by Trijiv** [comment]
Wow that was a fast reply. I will start testing this. I am using a Maximus 9 Extreme motherboard, 7700k OC to 5GHz @ 58degrees max, and 2 1080Ti in SLI all watercooled. ^_^
