### ISSUE TITLE
Call For Participation

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#57]
First, please read the exchange here between myself and the developer of Forknote here, 
https://github.com/forknote/monero-generator/issues/1

Second, please understand that just because we help out this project does not mean the TurtleCoin network has to go through a rebase once the work is complete. This is simply helping a friend who has already contributed to our project immensely.

What we're looking at here is not a finished product, but as @pmitchev mentioned, with some help, we can make it one. I've seen our community do a lot of big things, and I think this may bring helpful developments and needed insight for us should the community decide to help. https://github.com/forknote/monero-generator

Some context: TurtleCoin is a network created with the help of the Forknote project, which created and provided the tooling that allowed us to create our codebase from Bytecoin source code. Forknote project continues to have a reciprocal relationship with our community by providing updates and support to their software, as well as providing needed guidance to us when we've needed it most. It is important for us and, our duty to contribute everything we can back to this project to afford others the same opportunities we had when starting our network.

Monero, Forknote, and TurtleCoin all 3 share a common ancestor of Bytecoin, so we're all compatible to a degree in many different areas. Since their fork from Bytecoin, Monero has made a lot of strong, positive developments, and getting acquainted with their codebase, especially while we're currently discussing a rewrite of our core anyway, seems like a good idea, even if only as a learning exercise for our team in the process. The benefits could be strengthening our partnership with the Forknote Project, and possible use of the code improvements on our network once complete should the community decide this is the best idea.

Help and skills needed: C++, Test writing, CI/CD, more

Respond to this thread with any relevant skills you may have, or anything you can contribute that has not been listed.
https://github.com/forknote/monero-generator/issues/1

**Comment by Dreadmon** [comment]
Yes, this sounds interesting with the possibility of a very long term win.  I would like to get involved with C++ coding.

**Comment by brandonlehmann** [comment]
Please re-open if required.
