### ISSUE TITLE
Apply for Binance community coin

### ISSUE THREAD

**Issue by krruzic** [turtlecoin/meta#62]
I've mentioned this in the discord multiple times. I think this is our best shot to getting on a large exchange. 

https://support.binance.com/hc/en-us/articles/360000598531 details are at that link, basically a developer needs to fill out the application form, then the community can vote with 0.1BNB for Turtlecoin. The previous winners had vote totals that we could get. Maybe wait until the next voting session? https://www.binance.com/vote.html has previous results with Raiblocks at 12k.

NOTE: the current vote got delayed by the downtime so it should be possible to apply for this round even.

**Comment by pavelprudnikov** [comment]
Sounds interesting, I'm on

**Comment by RocksteadyTC** [comment]
Just my opinion, we are not ready for this yet.

**Comment by tbk176** [comment]
I agree we should only apply for the big exchanges when we are ready. How long do you think it will take to be ready for the big exchanges?

**Comment by pavelprudnikov** [comment]
What does it mean to be ready?

**Comment by tbk176** [comment]
Only Rocksteady and his team know if TRTL is ready. The whole philosophy of TRTL unless I'm mistaken is about having fun creating the product that is simple and accessible 
and the value will take care of itself unlike other coins/currencies that have no product?
I'm a believer in TRTL and believe the value is in the long term so I have faith and trust in the team.

**Comment by fexra** [comment]
@pavelprudnikov There is no set date or unified goal, but, TRTL are still very young. The dev team are still exploring the core code, and are even [debating on rewriting it completely in go](https://medium.com/@turtlecoin/this-week-in-turtlecoin-feb-17-2018-76485630c72c). Basic infrastructure such as wallets are still in development, and the community is still evolving at such a rapid pace, it's hard to say where we will be in say a month. I think we first have find stability, in both the product and the community, and be prepared when a massive influx of new users do arrive.
