### ISSUE TITLE
Mining Equipment

### ISSUE THREAD

**Issue by tbk176** [turtlecoin/meta#66]
@RocksteadyTC I listened to your interview on Block Zero with Kevin Rose and I was blown away with your vision and authenticity! I am a big fan of TRTL and your good self, so very best of luck with the project.
Anyways I have a question I already hold TRTL and I want to mine more TRTL to add to my balance. If I was buying a PC with 2GPU's what would you advise I purchase? 
Does the following matter:
1) CPU speed ie I3,i5,i7, i9 or Threadripper 1950x etc
2) GPU's what are the best cards?
3) What is a good motherboard
4) Does the broadband speed matter ie if I had a leased line (not shared) would that result in better #rates ?

I plan to buy an additional rig once the new Nvidia mining GPU's are released, but for now want to get going with mining using an efficient PC.

Best
tbk176

**Comment by timmcleod** [comment]
Hey @tbk176, welcome! You should consider popping into the TurtleCoin Discord (http://chat.turtlecoin.lol/) and visit the #help channel. Lots of folks there willing to help out.

**Comment by fexra** [comment]
Hey @tbk176, I'm myself no miner but we having a #mining channel on our Discord. I'm sure many people can share their knowledge with you over there :) Welcome to the TRTL community!
