### ISSUE TITLE
forum.turtlecoin.lol

### ISSUE THREAD

**Issue by adj-gh** [turtlecoin/meta#69]
I think a more efficient way to look at discussion on certain topics would be to have an actual forum by itself, apart from the meta issues.
This forum would be used mainly for discussion about the project, ideas, and announcements. meta/issues would remain as a bug tracking place for more of a fixing stuff approach. 
It would make it easier for people to contribute if they are not that familiar with GitHub and dismiss it as tech-savy stuff.
People who are not into using Discord would also have a go at contributing in a more friendly way. 
 
My proposal is to implement one of the following, if possible:
- [Flarum](https://github.com/flarum/flarum) 
- [Carbon Forum](https://github.com/lincanbin/Carbon-Forum) 
- [Discourse](https://github.com/discourse/discourse)

**Comment by RocksteadyTC** [comment]
I don't see anything wrong with it. Discourse is nice. If someone set this up I wouldn't be against it.

**Comment by fexra** [comment]
I think this would be a great idea.

**Comment by TRTLAlien** [comment]
I already made a forum that isn't very active. I'm open for it being used for whatever our TRTL needs are. http://trtl.freeforums.net/

**Comment by BebopTC** [comment]
I really like the idea of a forum. I don't think there is anything wrong with the one you created already, @TRTLAlien, but it may benefit from some topic adjustments etc

 two things of concern are availability and durability. if the forum is hosting any discussion that is important to project direction it needs to always be available and we can't really afford data loss, so those have to be addressed - best bet may be a platform that hosts forums as a service.

the 2nd is just overspread which can cause disconnect/isolation from  important discussions happening on different places, or dry one channel up. some of what you describe @adj-gh is similar to what meta issues already is, so we'd need to make sure the purpose of each channel is distinct.

the way i'm envisioning it is that we'd continue to use meta for more 'official' discussion, where devs and project contributors can really make decisions about the projects, and the forum being more general community discussion, ideas, etc where everyone can jump in - more so like discord, but less noisy and more structured
