### ISSUE TITLE
v0.2.2

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#7]
Discussion thread for bugs and talk related to v0.2.2

**Comment by RocksteadyTC** [comment]
# v0.2.2
### In this release: 

- [x]  red seed node issue fixed
- [x]  "Tx verification failed" fixed
- [x]  better import/export key stability
- [x]  wallet reset losing balances on early blocks fixed
- [x]  many small bug fixes
- [x]  checkpoint added to daemon
- [x] TurtleCoin Meta Discussion system added

Submit bugs: https://github.com/turtlecoin/meta/issues/7

Previous Announcements: https://github.com/turtlecoin/meta/labels/ANNOUNCEMENT

**Comment by CaptainMeatloaf** [comment]
The block unlocker marking blocks as orphaned appears to have surfaced again this build, and removing the +1 fix from the pool software doesn't seem to work. Investigating further.

**Comment by RocksteadyTC** [comment]
Blockchain and network still don't seem to be working @CaptainMeatloaf

**Comment by RocksteadyTC** [comment]
Core Dump on Ubuntu 16.04, verified by @gill3m

**Comment by RocksteadyTC** [comment]
Linux - https://github.com/turtlecoin/turtlecoin/releases/download/v0.2.2/TurtleCoin-v0.2.2-linux.tar.gz

Source - https://github.com/turtlecoin/turtlecoin/releases/download/v0.2.2/TurtleCoin-v0.2.2-source.tar.gz

Built this on a different machine with a different configuration.

**Comment by brandonlehmann** [comment]
Release in this issue has come and gone...
