### ISSUE TITLE
int.turtlecoin.lol

### ISSUE THREAD

**Issue by adj-gh** [turtlecoin/meta#70]
**A translation plataform for everything TurtleCoin**
Noticing the influx of people wanting to contribute with translating stuff, I think there should be a proper way to track what is done and for a more community way to do so.
Language can be a hard thing to do and everyone has their own style of doing so, a consensus like system would make things nicer and tidier.

Here are three ways in which this could be implemented:
- [Zanta](http://zanata.org/)
- [Weblate](https://weblate.org/)
- [Pootle](http://pootle.translatehouse.org/)

**Comment by yamiM0NSTER** [comment]
Jerme404 actually prepared turtlecoin.lol website for additional languages. I think it's better if we stick to github.
