### ISSUE TITLE
What social media should we be using? [QUESTION]

### ISSUE THREAD

**Issue by dethereum** [turtlecoin/meta#72]
So I was creating a social media bar that would link to all the official social media accounts that are listed on turtleturtle.org when I saw the FB link is not working. That made me think who really even uses facebook? I am of the opinion that we only really need Reddit/Github/Discord/Twitter. Does anyone agree with that opinion? Does anyone think we need more?

**Comment by TRTLAlien** [comment]
I would like to see us utilize Instagram a little more. I think with all the unique and funny memes we have it would be a great avenue to get those seen as it is built for pictures better than some of the other networks.

**Comment by derp-derp-derp** [comment]
TRTLmemes on insta would be awesome. I'd follow it.

**Comment by TRTLAlien** [comment]
Your wish is my command https://www.instagram.com/_turtlecoin/

**Comment by RocksteadyTC** [comment]
all of our official social channels are listed on http://turtleturtle.org

**Comment by Georgy64** [comment]
How do I sign in to my turtle coin wallet?
I've just created a wallet but don't have any idea on how to access it.
