### ISSUE TITLE
Stress/Benchmark Tool

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/meta#73]
So far I've found this: 
https://github.com/Huawei-OSG/caliper

From reading the docs the benchmark system does things a bit statically. I guess it is repeatable.

I was thinking agents spin up walletd, once synced, report to a master somewhere their address and wait for coins. Agents could either be small spenders or big spenders or dumpers on an interval. 

Because all agents report to a master their address's they can get or be notified when a new address is added. So they have somewhere to send to. 
 
Agents can also be told to mine or not, they would just mine themselves, since testnet low diff etc. 
 
So they just keep running sending coins. 
 
Stats can be collected. 
 
Stressing should be a matter of creating a new kind of agent and telling the others to send all coins to this new kind of agent. Once the stress agent gets enough coins then stress starts and others go back to what they normally do. 
 
If multiple stress agents. Then they co-ordinate by checking in with master and master picks a block height to start, stress agents start at that block height. 

All agents should be deployed via docker, this way if agent can ping the master, everything is good to go. Similar system to how rancher provisions hosts. 

```
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://<master-server-ip>:8080/v1/register/<registrationToken>
```

This way agent can also start other containers and gather stats.

**Comment by ZedPea** [comment]
How easy will it be to get this working with cryptonite? From a quick glance it looks like it doesn't support it yet. Or is the idea to implement this ourselves?

**Comment by SoreGums** [comment]
we would add cryptonote to the caliper project or build our own.

i would also like it to be simple for others to join in.
with what i propose anyone can copy/paste a command and join an existing master.

**Comment by RocksteadyTC** [comment]
If you need a test network for this, https://github.com/RocksteadyTC/testnet

**Comment by SoreGums** [comment]
That is the target rock and why I'm looking into this.

Another thing that might be worth collecting stats wise is to with probability of previous transactions being included: https://www.reddit.com/r/Monero/comments/70f07e/how_does_mixing_of_transactions_works/dn3xcz1/

**Comment by SoreGums** [comment]
so since this was first discussed a whole lot of information and ideas have been revealed.

the project Krang exists https://github.com/turtlecoin/krang/issues/1 and is still in the idea phase. This previous week went by far too fast.

I'm committed to bringing this to life. will keep making progress. if anyone wants to team up, ping me on Discord SoreGums#8071

closes this for now since the other project exists
