### ISSUE TITLE
Ledger Nano S Support

### ISSUE THREAD

**Issue by derp-derp-derp** [turtlecoin/meta#76]
Could we piggy back on the work Monero is doing to launch their Ledger Nano S app? Looking forward to the day I can stash some TRTL on my hardware wallet.

**Comment by fexra** [comment]
Let's do it buddy! Here is the Monero [pull request](https://github.com/monero-project/monero/commit/c7ace5fa3d412410312e21c55c28068dcd625fef) for Nano Ledger support from a quick search I did.

**Comment by brandonlehmann** [comment]
@zedpea this one's for you :)

**Comment by brandonlehmann** [comment]
https://github.com/LedgerHQ/blue-app-monero/

**Comment by wichtigwicht** [comment]
Is this still a thing? I want my TRTL on Ledger Live yeeeehaaaw!

**Comment by brandonlehmann** [comment]
You are welcome to help with the development effort. It's more likely to be accepted if we build it for them.

**Comment by wichtigwicht** [comment]
Ah okay i see, is there beeing worked on? Maybe i am the only one who wants this, dont know what the general opinion in the community is about this. I am not a developer, but i would like to spend some money for drinks and pizza for the development team if that helps!

**Comment by brandonlehmann** [comment]
I don't believe there is anyone actively working on it at the moment.

**Comment by RocksteadyTC** [comment]
That doesn't mean nobody wants it, that just means we have more important things we are doing right now.

**Comment by RocksteadyTC** [comment]
Any community member is free to start working on it or begin a bounty initiative

**Comment by woodyjon** [comment]
I'll have a look, and if I feel I am capable, I'll start working on it. The idea is to fork monero app?

**Comment by brandonlehmann** [comment]
That's one idea, yes. They've already done quite a bit of the heavy lifting I believe.

**Comment by wichtigwicht** [comment]
I looked at the #bounty Channel in the TRTL Discord. Apareantly there is already a bounty set for this:
https://www.imagebanana.com/s/1180/01eulo5K.html

I dont have 1MM in TRTL, my 4core miner is running 24/7 and i got 100k so far (joined the community 2 months ago). But woodyjon if i can support you with some money for the workinghours you put into that, i will buy some trtl.

**Comment by brandonlehmann** [comment]
@wichtigwicht The bounty is the award to the person or persons who complete the task. Anyone can contribute any amount to a new or existing bounty.

**Comment by wichtigwicht** [comment]
OMG, you are the best. Seeing this gaphic on the Ledger makes me happier than you think. Thanks so much for working on it!

**Comment by fexra** [comment]
Great job Jon!

**Comment by wichtigwicht** [comment]
@woodyjon yeah awesome! i set a bounty on that ^^ Not much but i am still looking forward to send you a pizza.

**Comment by lost-bro** [comment]
@woodyjon;  Damn fine job...... I'd love to see my TRTL on my Nano s.

**Comment by woodyjon** [comment]
Sorry guys, but I can't seem to port monero code for ledger into turtlecoin. The monero device lib is too intertwined with ring ct. I have the ledger app running, but I am unable to implement the stuff in the turtlecoin wallet code. It's crypto related code which is really too difficult for me.

**Comment by woodyjon** [comment]
On a side note, I will obviously not claim any part of the bounty. If someone can implement the stuff in the wallet code, even if using what I did on the ledger app (available on my github), everything is obviously for him. That is way more than the small changes I made to the ledger monero app.

**Comment by andreafno** [comment]
Maybe somebody at [FundRequest](https://fundrequest.io/) could implement this?

**Comment by RocksteadyTC** [comment]
It'd be more likely that we follow the obvious migration path to rct or bps

**Comment by JSterling8** [comment]
@LukeChilds - I know you worked a lot with Ledger for the Komodo interest claiming stuff. Do you have any recommendations for how TurtleCoin should proceed with this.

**Comment by lukechilds** [comment]
@JSterling8 sorry, I don't know much about TurtleCoin so don't think I can be of much help.

Is it just a Monero fork? If so you should be able to fork the Monero Ledger app and Monero GUI wallet, add any changes TurleCoin has made and go from there.

Although sounds like @woodyjon tried that it wasn't that simple.

How different (if at all) is TurtleCoin to Monero?

**Comment by JSterling8** [comment]
@LukeChilds - Thanks for the input. TurtleCoin and Monero share a common ancestor in ByteCoin, however there are significant difference in the codebases.

**Comment by lukechilds** [comment]
Ahh, in that case, it will probably be a significant amount of work.

Native Ledger app, API client and Ledger compatible wallet will all need to be built from scratch. The Monero Ledger stuff could serve as a useful reference, but forking it and basing your code on it will probably cause more issues than it's worth.

**Comment by TwixtedChaox** [comment]
Ok. I plan on starting this from scratch utilizing the coin as it stands right now. I have fully read up on the requirements and believe a "start from scratch" method is best. I can post a link to my gh repo shortly for those interested to watch changes

**Comment by brandonlehmann** [comment]
See https://github.com/turtlecoin/ledger-app-turtlecoin
