### ISSUE TITLE
RFC. Centralization problem

### ISSUE THREAD

**Issue by INITS-LLC** [turtlecoin/meta#79]
We faces the problem of centralization of the Turtle Network(TNet). Biggest pools(like Mine2gether) took under control whole network and regulary crash down TNet(last at 13:58 PM 23 March 2018).
Also we tried to find issue for protecting network while asic-resistance issue in progress and nicehash raids are inevitable. Now we are consolidating community resources on independent pool for further steps(entropool.com).
We thinking about fair and useful payment scheme for pool that may stimulate miners for decentralize and reinforce TNet.

What do you think about:
1) Delist pools which have hashrate much more greater than average value from https://turtle-coin.com/#pools ;
2) Payment method. Pool fee returns to all miners with rule "smaller hashrate -> bigger revenue" (check by IP) ;
3) Another way for increase stability of Turtle Network?

If you can, plz place 1card/rig in big pool(like mine2gether), add also 1card/rig in entropool.com for several hours and compare real revenue
I. Join us:
NsGpuCNMiner -o stratum+tcp://entropool.com:3333 -u YOUR_WALLET_ADDRESS -p x
ccminer -o stratum+tcp://entropool.com:3333 -u YOUR_WALLET_ADDRESS -p x
or edit your XMR-Stak config-file
II. Post your results here

Make TurtleCoin Great Again )

**Comment by CaptainMeatloaf** [comment]
This reads like an advert for your pool, not a discussion about centralisation. This issue tracker is not for adverts, so please reword it.

Here's an idea - you talk about smaller hash rate bigger reward, what's to stop a large miner just running each card as a miner individually and just using a load of proxies? Public proxy lists are available which could easily support this.

**Comment by INITS-LLC** [comment]
Several times I ask community:
"What do you think about:
1) Delist pools which have hashrate much more greater than average value from https://turtle-coin.com/#pools ;
2) Payment method. Pool fee returns to all miners with rule "smaller hashrate -> bigger revenue" (check by IP) ;
3) Another way for increase stability of Turtle Network?"

Community choice: DO NOTHING

Today mine2gether rewrite several blocks again, difficulty is 500M

**Comment by sumlnoether** [comment]
Rewrite several blocks? You sound ridiculous.

Mine2gether is a very fair and well-run pool. Take your baseless allegations elsewhere.

**Comment by RocksteadyTC** [comment]
Do not spam the chat with this bullshit.

**Comment by INITS-LLC** [comment]
What spam you talking about? Investors pay money to small miners via pool for decetralization

**Comment by SoreGums** [comment]
In short. Create a pool talk about it in the discord chat.
If people like it they will join your pool.

Coming here and saying there are problems that are opinions (just because u think they are true doesn't make it true for others) and advertising your thing, doesn't work.

If you want to discuss it, do it on discord, if you don't like the answers or what people say, wait 12hrs for timezones to do there thing and have a chat with other people, if the feedback is still not what you want to hear maybe you'll need to adjust what you believe?

**Comment by INITS-LLC** [comment]
Rock banned me in discord ))
