### ISSUE TITLE
TODO for turtle-wallet [python]

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#8]
https://github.com/turtlecoin/turtle-wallet/issues/7
**Code behind for the Send TRTL tab**
Currently the tab for sending TRTL does nothing, as there is no code behind to handle the signals from the UI.
These signals need to be handled so that TRTL can be sent, and any errors in sending need to be handled correctly.

https://github.com/turtlecoin/turtle-wallet/issues/8
**Opening and closing a walletd process alongside the wallet**
This wallet interacts with walletd for it's features. Right now, it requires the user to start up their own instance of walletd.
We need to detect if there is a walletd process already running and if there isn't, start one up as a child process (and close when the wallet is closed).
We also need to track the syncing state of walletd so that users are aware of what is going on and why their transactions aren't appearing if they are opening the wallet for the first time on a particular machine, or their machine is behind and still syncing.
Feedback is welcome on this issue as I probably missed a few things here.

https://github.com/turtlecoin/turtle-wallet/issues/9
**Settings Page**
A settings page is required, most likely when the other features (like a walletd child process and key imports) are implemented.
Settings on this page TBC, comments welcome.

https://github.com/turtlecoin/turtle-wallet/issues/10
**Importing keys into the wallet**
It would be useful to be able to import keys into the wallet, in order to maintain compatibility with simplewallet and the QT wallet. This would also allow us to avoid issues such as people trying to import their own wallet files, etc.
My proposal would be to allow users to import keys and turtle wallet will handle the wallet file, etc. itself.

https://github.com/turtlecoin/turtle-wallet/issues/11
**Incremental refreshing of data**
Currently the way data is refreshed is that it clears everything and just resets the values of everything.
It would be useful to only update things if they have changed, so that the transaction list is actually scrollable and doesn't get reset every 5 seconds.
My proposal is to have a hidden column for the transaction/transfer hash/id in the transaction list store and only insert/delete the records that have changed (note deletion has to be supported too in case the client's daemon has accidentally forked and listed some transactions that are 
invalid).

https://github.com/turtlecoin/turtle-wallet/issues/12
**Gracefully handle exceptions**
Currently there is no exception handling, and the entire thread on which there is an exception is lost.
Proper exception handling is needed.

**Comment by brandonlehmann** [comment]
These comments belong on https://github.com/turtlecoin/turtle-wallet-python
