### ISSUE TITLE
Labeling of issues that were resolved

### ISSUE THREAD

**Issue by yamiM0NSTER** [turtlecoin/meta#80]
Hey,

I have a suggestion. Whenever issue is resolved, it could have a label saying "Ready in next release" or something along the lines. That way we can keep the issues open and close them after new version of something is released so in case someone finds a mistake or a problem with the solution they don't have to open new issue for that. It would also make it easier for outsiders to see how active the community is.

Just my 2 cents,
yamiM0NSTER.

**Comment by RocksteadyTC** [comment]
Good idea! Adding a PENDING RELEASE label

**Comment by yamiM0NSTER** [comment]
Make sure to add label in other repositories aswell! :)

**Comment by SoreGums** [comment]
the labels were created - however, they aren't being used as described 😆 
not much to do about that though...

going to close this issue then
