### ISSUE TITLE
Date and time of transfers in simplewallet

### ISSUE THREAD

**Issue by pavelprudnikov** [turtlecoin/meta#82]
It was in old version, but now it's gone.

**Comment by ZedPea** [comment]
I'm fairly sure the old version was incorrect and was just printing out the logging timestamp? There isn't a timestamp embedded in the transaction, so the best you could do is get the timestamp of the block it's included in.

I'll look into adding it.

**Comment by ZedPea** [comment]
Added in https://github.com/turtlecoin/turtlecoin/pull/161
