### ISSUE TITLE
dev blog should be a medium publication, not a medium user account. 

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#84]
As I read and react to other people in the community's articles on the dev blog account, I'm noticing it showing up in the blog.turtlecoin.lol feed and breaks up the flow of articles there. I'd like to move all the articles to the publication page I've created, and continue there. We have better visual control over the dev blog this way, and I can assign roles to editors and writers to be able to log in on their own.

Anybody who actively publishes on a medium publication account have anything to say? Tips or tricks? Comments?

**Comment by SoreGums** [comment]
no experience.  
$0.02

it seems like the publication route is the way to go though.  

here is one [1] that is just a five-part tutorial, so the articles showed up without all his personal account activity getting in the way. so probably makes sense to hit go on this when you have a moment.

https://medium.com/peep-stack

**Comment by brandonlehmann** [comment]
Blog moved to Wordpress. Still need this?
