### ISSUE TITLE
Wrong meta description appearing in Google search

### ISSUE THREAD

**Issue by mysticaltech** [turtlecoin/meta#85]
Hello @RocksteadyTC, you have 2 meta tags in the head of your main site turtlecoin.lol:

`<meta name="description" content="TurtleCoin">`

`<meta name="Description" content="TurtleCoin is a fun way to send money privately to friends or businesses. TurtleCoin is a community-developed, open source cryptocurrency that is easy to mine, has a graphical wallet, and is listed on exchanges for trade.">` 

Obviously, the correct one should be the second one! But Google uses the first one.

![screen shot 2018-04-18 at 12 11 30 pm](https://user-images.githubusercontent.com/518555/38926383-cac30a60-4302-11e8-94d9-46d98319e5ca.png)

So just remove the first one.

Regards and keep up the good work! Love you coin.

**Comment by SoreGums** [comment]
This is weird if check the [source code in github](https://github.com/turtlecoin/turtlecoin.lol/blob/master/index.html), it isn't there.  
then if check headers, last modified is Feb 18.  

So looks like code in github has not been pushed to wherever the site is being hosted.  

@RocksteadyTC maybe push an update?

**Comment by ar-x** [comment]
It could be that recent updates to the site fixed this issue. This issue can now be closed. We also have [another issue](https://github.com/turtlecoin/turtlecoin.lol/issues/17) to ensure that SEO, social sharing previews, etc. all work properly. Feel free to point out things we can improve on there.

---
<img width="582" alt="one" src="https://user-images.githubusercontent.com/37969038/40595866-0adde752-61ec-11e8-8fa6-2e3c4f1cb421.png">
