### ISSUE TITLE
Create COMMUNITY PROJECT indicator for projects hosted on the main github org

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#86]
community.turtlecoin.lol should point to a page on github or something that explains what a community project entails. Every community contributed project should refer to this URL in the main header of their project, on github.

The page should cover: 

- what does community mean,
- how to contribute, 
- how to report a bug, 
- how to get help,
- explanation of risk

![image](https://user-images.githubusercontent.com/34389545/39345600-02da659e-49af-11e8-81f4-6b60d63caf2f.png)
![image](https://user-images.githubusercontent.com/34389545/39345593-f8b16ad6-49ae-11e8-8117-8d0ceed31a77.png)

**Comment by RocksteadyTC** [comment]
# TurtleCoin Community Projects
### This document will explain what we mean when we say something is a 'TurtleCoin Community Project'


_NOTE: If you're taking the time to read this document, I already like you, because you saw the word "Community" and you had to click it. Please say hello in the chat when you make an account, we'd love to meet you! [chat.turtlecoin.lol](http://chat.turtlecoin.lol) :smiley_cat:_ 


- What does 'Community Project' mean?
When we mark a repository as a "Community Project", it signifies that this is a project created and maintained by a TurtleCoin community member. Usually it is a volunteer effort of one or more community members. There might be periods where the developers of a Community Project get busy during finals in school, or have to finish up a large deal at the office, and updates might not come out as often as a full time dev team would produce. Usually this isn't the case, and these projects become a labor of love, so we hope this document shows you how to submit new feature requests for your favorite projects, and maybe even fix a bug or two!


- How to contribute to a project you like
You might see a project you like that needs a better readme, or has spelling mistakes in the directions, and maybe if you're feeling generous you'd like to see it fixed, great! We make this really easy on all of our projects. For those of you not familiar with Github, you can click the little pencil on the document you want to submit a correction for, and it will create a copy for you to edit and then submit as a "pull-request". 
Sounds scary! This is really just you seeing an error in a book, copying the page and adding your corrections to it, and then sending it back to the publisher. 

![image](https://user-images.githubusercontent.com/34389545/39613145-cc83d420-4f54-11e8-86a4-67e29ff746d6.png)
(In this image, if you wanted to complete the empty README file with directions or a guide, you could click the pencil icon on the right, and the interface walks you through submitting your changes as a pull request!)

_TIP: Some 'contributors' who submit corrections, and some 'developers' who submit code patches will notice that their username in the community discord changes color... and mysterious abilities may appear... This is normal :) Shhhh!_

- How to report a bug
This is probably one of the most important things a person can do to help us. When people come to us and say, "here are my skills, how can I help?" it makes it really easy for us to point at your bugs that you've submitted and say "hey, so-and-so pointed out this mistake in this program, can you fix that?" and usually they take care of it right away. The first step in fixing something that's broken is saying something! You can submit a bug report by clicking the button at the top of the project called ISSUES, and then creating a new issue. 
![image](https://user-images.githubusercontent.com/34389545/39613306-b62696e4-4f55-11e8-80a1-960b1928227b.png)
_TIP: The best issues say more than "it's broken.". They say: what operating system, what version of the program broke, what were you doing when it broke, include a screenshot if possible of the error you see, or copy and paste the log files. The more information you include, the better your issue will be able to be addressed, and we are so thankful for your time writing them._


- How to get help
If you've submitted an issue, and you don't quite know how to fix it on your own, and you just need someone to help you, we've got a few channels to help with that in our chat. [chat.turtlecoin.lol](http://chat.turtlecoin.lol)

1. For general help, try #help
2. For mining help, try #mining 
3. For help with your program you're developing, try #dev_general
4. For your cool logo, marketing plan, try #dev_marketing

TIP: Some people will notice that when they spend time helping in these channels that a robot may drop by and fill their pockets with some shells. We want you to spend time helping people and doing nerd stuff to help the project, so it only makes sense that it rains the most in these rooms :)

- Explanation of risk
There is always a risk that the person running the project you're using has embedded super secret nuclear missile plans that they hacked out of a Russian datacenter, but odds of this are slim, and it's never happened. We'd be stupid to say there isn't a risk that someone contributing to a community project, through no fault of their own, creates a bug that corrupts your wallet file (backup your keys!) or otherwise causes things to mess up on your system. However unlikely this is to happen, we want to error on the side of responsibility and advise you of the potential for mistakes like this, and we ask that you please back up your spend key, view key, and mnemonic seed somewhere very safe just in case we mess up the nuclear-blueprint-hiding-algorithm and blow up your router in the process. Our keyloggers are top notch. 


Thanks for reading this, if you got down this far, please say something in the chat to be showered with emojis.

**Comment by SoreGums** [comment]
grammarly and my minor edits https://gist.github.com/SoreGums/1908bc21466a37c7be2df3a7373cf33d/revisions - the whole paragraphs are commas added or removed.

**Comment by SoreGums** [comment]
Github > GitHub: https://gist.github.com/SoreGums/1908bc21466a37c7be2df3a7373cf33d/revisions

**Comment by SoreGums** [comment]
looks good rock
might need details, not sure - a case of how to read this as someone who doesn't GitHub or even git or even codes or even thinks about "using" software.

bit a of a difference between taking a page out of a book, writing on it and sending it somewhere and doing the equiv in GitHub

**Comment by RocksteadyTC** [comment]
We should link to a wiki page on how to submit a PR to TurtleCoin, how to submit an issue to a Community Project, and so on. I'll pay 10k per page for whoever wants to write these in the wiki.

**Comment by RocksteadyTC** [comment]
Added your changes btw.

**Comment by SoreGums** [comment]
makes sense

how to docs as per publishing to the wiki is ongoing
https://github.com/SoreGums/turtlecoin-wiki/blob/how-to-contribute-to-wiki/guides/How-to-contribute-to-the-TurtleCoin-wiki.md

**Comment by SoreGums** [comment]
you have created a new GitHub repo, 

What is the vision here?
and is turtlecoin/turtlecoin/wiki _(>turtlecoin/turtlecoin-wiki)_ for TurtleCoin the project or is it's scope focused on specific things.

How come this project thing is not in the docs and a separate thing?

**Comment by RocksteadyTC** [comment]
I'm not sure, I did what I thought was best at the time. Put it wherever you like and update me with the link and ill change the CNAME forward so that community.turtlecoin.lol points there

**Comment by SoreGums** [comment]
I wrote some words in the turtlecoin-wiki rename https://github.com/turtlecoin/meta/issues/91#issuecomment-388666516

In summary: I think this effort wuld be best placed in the central repo for all project documentation :)

**Comment by ar-x** [comment]
Maybe use a badge on such projects ;)

[![Community Project](https://img.shields.io/badge/TurtleCoin-Community%20Project-2ecc71.svg)](https://github.com/turtlecoin/community-projects)

```md
[![Community Project](https://img.shields.io/badge/TurtleCoin-Community%20Project-2ecc71.svg)](https://github.com/turtlecoin/community-projects)
```

**Comment by brandonlehmann** [comment]
I believe this wins:

[![Community Project](https://img.shields.io/badge/TurtleCoin-Community%20Project-2ecc71.svg)](https://github.com/turtlecoin/community-projects)
