### ISSUE TITLE
Changing WebAPI format (JSON) to the Protocol Buffers format.

### ISSUE THREAD

**Issue by XMks894** [turtlecoin/meta#88]
What are protocol buffers?
Protocol buffers are a flexible, efficient, automated mechanism for serializing structured data – think XML, but smaller, faster, and simpler. You define how you want your data to be structured once, then you can use special generated source code to easily write and read your structured data to and from a variety of data streams and using a variety of languages. You can even update your data structure without breaking deployed programs that are compiled against the "old" format.

more on this site https://developers.google.com/protocol-buffers/docs/overview

and some example structure in C#:

frontend model => can be use like that but also we can use protobuff model => it depends on our beauty of code.
```
public class ErrorMessage
{
    public class ErrorC
    {
       public int Code { get; set; }
       public string Message { get; set; }
    }

    public ErrorC Error { get; set; }
    public object Id { get; set; }
    public string JsonRpc { get; set; }
}
```

frontend and backend protocol definition of Error message from WebAPI, some example:

```
//to be know what we should parse or/and what we need to send to the communication protocol
public class MessagesType
{
  public const Byte MESSAGE_TYPE_ERROR_MESSAGE = 1;
  ...
}

[ProtoContract(UserProtoMembersOnly = true)]
public class ErrorC
{
   [ProtoMember(1, IsRequired = true)]
   public int Code { get; set; }

   [ProtoMember(2, IsRequired = false)]
   public string Message { get; set; }
}

[ProtoContract(UseProtoMembersOnly = true)]
public class ErrorMessage
{
   [ProtoMember(1, IsRequired = true)]
   public ErrorC Error { get; set; }

   [ProtoMember(2, IsRequired = false)]
   public object Id { get; set; }

   [ProtoMember(3, IsRequired = false)]
   public string JsonRpc { get; set; }
}
```

**Comment by brandonlehmann** [comment]
We’ve had some talks about this on discord. 

I’m currently working on a websocket implementation for the daemon and am debating doing it with protobuf payloads.

**Comment by XMks894** [comment]
yes, sounds good. I have a strong skills in that area - but not in WebSocket - I'm using protobuff structures in Socket server.

**Comment by rwdim** [comment]
Excellent plan... always nice to be able to add support for new things without having to drag 50 versions of changes with you.

**Comment by XMks894** [comment]
@rwdim what you mean "50 versions of changes with you"?

**Comment by rwdim** [comment]
@XMks894 Just that if you don't do it the way that is proposed, you end up having to test each viable back-version to ensure the change doesn't break something.

**Comment by brandonlehmann** [comment]
At some point though, you have to cut the umbilical cord and commit to the new and cut off the old; however, that changeover must be planned and executed well. More importantly, the community must be given more than adequate notice to update their software as well as any tools dependent on the current implementation(s).

**Comment by XMks894** [comment]
I understand - for me it's obvious - every day at work is planning how to avoid fragmentation.

**Comment by RocksteadyTC** [comment]
@XMks894 Imo, we could use some help in that regard. Thanks for contributing, I hope we can take advantage of that to help streamline some of our software. Are you in the discord per chance?

**Comment by brandonlehmann** [comment]
WebAPI won't change any time soon as JSON is just too easy for web browsers and other application stacks. I've got a branch where I'm working on integrating protobufs into the wallet/daemon communications
