### ISSUE TITLE
v0.2.2 Ooze GUI Wallet

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#9]

**Comment by RocksteadyTC** [comment]
`[Wallet] Load wallet error: The password is wrong`

Whether password is right or wrong, you'll get this output and the wallet loads.

**Comment by RocksteadyTC** [comment]
Fusion Transactions are working when they don't contain a spent key image.

**Comment by RocksteadyTC** [comment]
# Ooze wallet reflects the wrong balance
### follow these steps to reproduce

1. `./TurtleCoind`
2. `./simplewallet # log in to a simplewallet with a large balance`
3. `./Ooze-v0.2.2-linux`
4. Check balance
5. Reset wallet
6. Check balance
7. Close Ooze
8. in Simplewallet, type `balance`


Balance should be different. I had not been able to produce a pattern or reason for this.

**Comment by brandonlehmann** [comment]
That's nice... can we close this?
