### ISSUE TITLE
rename turtlecoin-wiki to turtlecoin-docs, thoughts?

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/meta#91]
it has already been brought up.

thought I'd just highlight it here.

this repo is the source for writing about TurtleCoin project.
- so far it has guides.
- API for walletd, daemon, etc are being actively worked on now
- it will be the place for dev docs about the code
- potentially news articles are going to end up in here #18
- I think it might work to have the community items in there too #86

It makes sense to have any written content in markdown, github flavoured markdown is particularly nice as it has a detailed [spec](https://github.github.com/gfm/) and can use gists or any of the text inputs to see how it could be rendered.

Being that items are arranged mostly logically, creating dedicated front ends or renders of the content is mostly straight forward (takes some time to create the first pass, after that scripts take over and keep things updated).

Finally the attraction of using git repositories for content is, once it is familiar, the workflow is straightforward and editing or creating new content and putting it in place "just works". A lot of issues around multiple people coming and going is solved by using git.

so yeah, -docs? or anything else that covers the above areas? let's figure it out this week and take another step forward in the epicness that is the TurtleCoin project :)

**Comment by Sajo811** [comment]
* mkay
* mkay
* will the code be in this repo or another one? There was talk about keeping 2 seperate domains for the website

Community, if there are a lot of, can come in their own "page", or come under "community"(this is in reference to my wiki frontend)

I'd rather keep it as turtlecoin wiki, and the other one as turtlecoin dev docs

**Comment by ar-x** [comment]
> potentially news articles are going to end up in here #18

hmm i was thinking about keeping news, events, blog posts type of things out of this repo - in its own repo.

**Comment by RocksteadyTC** [comment]
It sounds like we have 3 discrete lanes of written content, with the latter two being more inter-related than the first: 

- **blog** (medium: roundups, interviews, etc)

and 

- **developer documentation** (API and RPC resources, technical spec)
- **user documentation** (howto's, guides, tutorials)

Words like wiki, docs, knowledgebase, can sound ambiguous to a non-english speaker, and invites subjective interpretation for someone who isn't already initiated or familiar with the nuanced differences between the terms. Subjective definitions for these labels may be the source of some of the confusion between us about "well, why doesn't this content belong *here* with this other stuff instead of *here* where I think it belongs". 

>There was talk about keeping 2 seperate domains for the website

TurtleCoin.lol is our website.

**Comment by SoreGums** [comment]
**rename impact**  
the url and the name changes only, being a git repo the content stays the same. said another way. instead of the clone/remote URL being https://github.com/turtlecoin/turtlecoin-wiki.git it will be https://github.com/turtlecoin/turtlecoin-docs.git. you can do this on any of your repositories it is purely cosmetic.

so in your existing checkouts you can just update the URLs in .git/config. git operates on the content not the URLs.

**separate all the things**  
With regards to documentation/guides/api type things, not really keen on separating it at the source, seems like it would make things difficult for no reason other than "because". I don't have a concrete reason to keep it together, other than to say "all of that kind of thing is here, in this repository". How people want to present and exclude or included or make content look different is fine, take what fits your goal and exclude what doesn't or make it look different as needed.

**news, events, blog posts - ephemeral type of thing, own space/source/repo**
Yeah, I see the point there. 👍 

And Rock's comment clears up the areas nicely.

So circling back to the topic here.  
Does turtlecoin-docs suit?
- **developer documentation** (API and RPC resources, technical spec)
- **user documentation** (howto's, guides, tutorials)

or is there another term that would be best? I think wiki isn't accurate, hence bringing this to the top of the conversation.

**Comment by SoreGums** [comment]
oh forgot about the community part #86 

as well as those two, **user**/**dev** docs, what about other TurtleCoin project items that aren't News, Events, Blog post types?

Since whatever is in the community idea, it is probably going to get guides, and those guides fit nicely into the **user** docs area. we already have other pages on the user docs side that aren't purely guides or howto which are relevant and informative about the project at large.

All that is to say, does **-docs** cover it all off, or do we stick with wiki _(even though it is not a wiki? in terms of editing behaviour)_  
There is this line in the README.md on the repo after all  
![image](https://user-images.githubusercontent.com/317/39973149-5c52ebba-5746-11e8-912a-5495b0a9acec.png)

Then read the blurb describing it:
> This repository is the official home of all TurtleCoin documentation and should be regarded as the single source of truth for all 'official' or officially supported TurtleCoin projects. Because of the distributed, open, community-driven nature of our development teams, we believe the easiest approach to managing our documentation is to organize all of it in this central repository. This helps to avoid duplication and inconsistency and relieves contributors from having to track down and edit multiple documents in multiple places.

I think that covers it all then

**Comment by ar-x** [comment]
> Does turtlecoin-docs suit?

👍 . Works!

Just so to point out the alternative here (not that I'm biased)

turtlecoin-dev-docs
turtlecoin-user-docs

along with

turtlecoin-media-docs (news, etc)
turtlecoin-community-docs

I'm fine whichever way.

**Comment by Sajo811** [comment]
I guess turtlecoin-docs would be alright as a repo for the dev and user docs, imo they should be hosted on different domains or as I described before (buttons)

Media and community docs should be in (a) different repo(s).

Alternatively, you could follow ar-x's idea 

Alternatively you co

**Comment by RocksteadyTC** [comment]
Please explain more about why you feel we need new domains?

**Comment by Sajo811** [comment]
Leaving them both on the same domain, or on the same page(visible in the sidebar on as a top on the top) may confuse newcomers/newbies. Not only that, but dev docs have a lot of information and lot of syntax. It would be better to let each of them have their own frontend, again achieveable only on seperate domains or using the "tab" feature i explained above @RocksteadyTC

**Comment by ar-x** [comment]
From a purely technical point of view  – would just like to point out that some of this is tricky to implement. I would rather see something shipped in a *reasonable* way and see it get used rather than achieve perfection. And perhaps then refactor to achieve whats needed then.

I primarily say this because I'm planning tackle a lot of this ;), and don't want to waste my time (no offense, just the reality - I really want to move the needle on all of this).

The main put off is this:

> As far as any visitors/viewers are concerned the docs present as a coherent whole, however behind the scenes they are most likely rendered by different engines.

I see a subdomain per repo as easy to do, and a reasonable first step. We would make sure that they look same *look* the same (there are different ways of doing this). I expect 3 repos - user guides, dev guides, api docs.

I would like to understand how stringent we are going to be on this specific aspect. I understand that these projects would represent TurtleCoin, so it would need a bunch of people to agree.

Of-course, its a do-ers market, so I'm all for it if there is a better implementation.

**Comment by SoreGums** [comment]
>From a purely technical point of view – would just like to point out that some of this is tricky to implement. I would rather see something shipped in a reasonable way and see it get used rather than achieve perfection. And perhaps then refactor to achieve whats needed then.

Any details on this?
From what I understand, md goes in, html comes out, html files put somewhere.  
if it is about links, all lins are known - they are all the same, they can be machined into anything. 
if it is about images, the same thing applies as far as paths are concerned.  
the gfm format is well documented.  

if only the api is needed, then grab the api directory of md files and make html.  
if it is just the user side of things about guides and how to, delete the api directory on the clone of the repo. if there is a link to api docs then make sure it points wherever api shows up in the frontend.  

I see the source material as very structured and easily machine-readable, so therefore anything can be done to it with a machine. It seems you have a different take on this, so am keen to learn where I've got blind spots on this.

The only thing I see being "different" in terms of theme and template are the API docs where a slate style theme works well to interact with the material, everything else is just words talking about ideas. The whole heading, paragraph maybe a table and some images sprinkeld in can apply to all: how to user guides, things talking about the different projects, summary pages with links to other content, dev specific hand holding to get started (gfm has three backtick code colour highlighted pre tags etc).

All that needs to be figured out is the menu/navigation. I think a unified one is possible, a mega menu at the top might even be the way to go to quickly get somewhere, then secondary sidebar navs can take over from there, with in page ToC boxes.

**Comment by SoreGums** [comment]
also - the issue I see with getting all this content into a frontend is the design itself.

someone come up with a complete design to satisfy all the requirements - then a lot more people are avilable to fill that design up with content. there are not many people around here who can figure out this design though. I can PSD anything to html and make it pixel perfect to the design, I can't come up with the design though.

**Comment by ar-x** [comment]
> Any details on this?
From what I understand, md goes in, html comes out, html files put somewhere.
if it is about links, all lins are known - they are all the same format/structure maps can be created, they can be machined into anything.
if it is about images, the same thing applies as far as paths are concerned.
the gfm format is well documented.

My main point here was that it can be done, just that its not the easiest path. For example,  the assets produced by the frontend sites might conflict.  These frameworks like Slate for example, come with their own CSS, images etc. - which sourced from root. It can ofcourse be modified, but better done later.

**Comment by ar-x** [comment]
> I see the source material as very structured and easily machine-readable, so therefore anything can be done to it with a machine. It seems you have a different take on this, so am keen to learn where I've got blind spots on this.

Keep in mind that the source material is markdown (which gives us HTML) which in itself is unstructured, its only structured by the way of our conventions, unlike JSON etc. So it would be tricky to design independently of this fact. There are some nice designs which perfectly fit in for our use-cases though.

**Comment by Sajo811** [comment]
@SoreGums Yup pretty much accurate, except the community part. Somethings overlap and deserve to be in *user-docs*, while other deserve to be in community, and some explicitly in either side. In my opinion, some guides like how to contribute should be in (present day) turtlecoin-wiki, but not be rendered in the frontend (GH Wiki for now) - there can be a "help contribute!" link linking to the .md file in the repo

Then there are some things which users should know, so these can be rendered in the front end but not given much importance in the sidebar, and will redirect to someother domain/community docs(llike woocommerce)

**Comment by SoreGums** [comment]
> Yup pretty much accurate, except the community part. Somethings overlap and deserve to be in user-docs, while other deserve to be in community, and some explicitly in either side. In my opinion, some guides like how to contribute should be in (present day) turtlecoin-wiki, but not be rendered in the frontend (GH Wiki for now) - there can be a "help contribute!" link linking to the .md file in the repo

This doesn't make sense to me. Specifically.

`I'm on a page that looks all nicely TRTL branded, click a link now I'm on a completely different look and feel site branded GitHub. The content is still just words talking about TRTL things, what gives?`

I don't understand the desire to have multiple locations for everything. It is akin to being given a book on cars. Yet if you want to read about Ford you have to go to a 7/11 store and ask the clerk for the Ford section which is chained to the counter. For some reason it was never included in the cars book.

>Then there are some things which users should know, so these can be rendered in the front end but not given much importance in the sidebar, and will redirect to someother domain/community docs(llike woocommerce)

OK, I'm still struggling with why clicking Community Projects takes people off to the 7/11 store. Why are the users so fragile they can't handle reading about Community Projects? Why do the people who are interested in the Community projects need to go to the 7/11 Store to read about them when they can easily be included in the original cars book they have right in front of them?

**Comment by SoreGums** [comment]
Thanks @ar-x - Everything you've said is what I thought, and is reinforcing my belief given a design and a directory of like documents that need to follow that theme design, they can live next to another directory of content that  follows a different theme design and all cross-link each other under the same overall navigation/ site/domain.

> It can ofcourse be modified, but better done later.
If this gets to the point of "hey we have these frontends all done - let's merge them into a cohesive whole" I'm not seeing that going to take much effort.

> There are some nice designs which perfectly fit in for our use-cases though.
tell me more @ar-x . I'm guessing the slate one is for the API

**Comment by ar-x** [comment]
> There are some nice designs which perfectly fit in for our use-cases though.
tell me more @ar-x . I'm guessing the slate one is for the API

Yes, Slate is for API - luckily we didn't have to customize it too much because that design style has become quite the standard for API docs.

Guides though are a different beast. There are a lot of variations in design based on the nature of content. 

For example our User guides is a collection of guides, rather than a guide on a specific topic. A good site which implements which pattern is https://docs.bugsnag.com. You are presented with top level categories and then sub-categories and then the actual guide. And the top breadcrumb tells you where you are at any point.

I'm still mulling over things. Let me know if there are example sites you admire.

**Comment by ar-x** [comment]
Heroku docs – https://devcenter.heroku.com/categories/reference, Ruby On Rails docs - http://guides.rubyonrails.org/ are other examples of such a pattern.

**Comment by SoreGums** [comment]
I really like this layout for a **guide** http://guides.rubyonrails.org/getting_started.html
The rails guides have a limited "other things" so lumping them under _digging deeper_
Guide Index, mega menu is what I could seeing being a top level item for different areas as well, if not the whole thing.

The bugsnag makes a lot of sense too. They have someone in charge of that, cause every single page is the same content/words wise. Looking at our guides, they are free flowing ;) The breadcumb seems like the path determines where things are. so just arranged in directories, breadcumb sorted.

**Comment by SoreGums** [comment]
so the week is up - let's rename this repo from turtlecoin-wiki to turtlecoin-docs @RocksteadyTC @BebopTC :)

**Comment by ar-x** [comment]
I'll leave it to your judgement though. Since eventually we'll end up like that.

**Comment by RocksteadyTC** [comment]
Done 

@SoreGums 
@ar-x

**Comment by RocksteadyTC** [comment]
oops
