### ISSUE TITLE
Turtle Chat Ranks

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#94]
We have added a chat levelling system that applies different ranks for different user levels. Rank 2 is called Turtle. What should the other ranks be called? 

### Fill this in

- lvl 2     - "Turtle"
- lvl 4     - __________
- lvl 8     - __________
- lvl 16   - __________
- lvl 32   - __________
- lvl 48   - __________
- lvl 64   - __________
- lvl 80   - __________
- lvl 96   - __________
- lvl 100 - __________

**Comment by SlipperyButters** [comment]
The first few levels go by really fast right? Maybe the second named level should be around 16 and then leave the rest as is, because people are already level 10-12 from one day of posting since we started the bot.

**Comment by clickercake2** [comment]
lvl 2 - "Baby Turtle"
lvl 4 - "Learning Turtle"
lvl 8 - "Turtle"
lvl 16 - "Advanced Turtle"
lvl 32 - "Blue Turtle"
lvl 48 - "Super Turtle"
lvl 64 - "Turtle Overseer"
lvl 80 - "Turtle Wizard"
lvl 96 - "Dedicated Turtle"
lvl 100 - "Turtle King"

**Comment by ereptor81** [comment]
I got nothing for the majority of them, but I propose resetting the first color to level 8:
lvl 2 - Egg
lvl 4 - Hatchling
lvl 8 - Turtle

**Comment by bearybullish** [comment]
lvl 2 - "Turtle Apprentice"
lvl 4 - "Who's a Good Turtle?"
lvl 8 - "Upside Down Turtle"
lvl 16 - "Novice Turtle"
lvl 32 - "Comfy Turtle"
lvl 48 - "Having a Mid-Turtle Crisis"
lvl 64 - "Advanced Turtle"
lvl 80 - "Turtle Gang Turtle Gang"
lvl 96 - "Notice Me Sendai Turtle"
lvl 100 - "Master Turtle"

**Comment by zack796** [comment]
I like Ereptor's idea with the first 3 ranks just adding to that

lvl 2 - Egg
lvl 4 - Hatchling
lvl 8 - Turtle
lvl 16 - Snapper
lvl 32 - Terrapin
lvl 48 - Hawksbill
lvl 64 - Loggerhead 
lvl 80 - Leatherback 
lvl 96 - Tortoise 
lvl 100 - Archelon

**Comment by BrandonT42** [comment]
Master Splinter for level 100, need some TMNT references up in here

**Comment by holytastyguacamole** [comment]
lvl 2 - Egg
    lvl 4 - Hatchling
    lvl 8 - Turtle 
    lvl 16 - Speckled Turtle
    lvl 32 - Box Turtle
    lvl 48 - Snapping Turtle
    lvl 64 - Sea Turtle
    lvl 80 - Galapagos Turtle
    lvl 96 - Leatherback Turtle
    lvl 100 - Master Turtle

I reckon ninjas/TNMT references should be reserved for Devs

**Comment by Genesus** [comment]
I think it should be a combination of species and titles like grandmaster, sage and what not. I also agree with others when they say that "Turtle" shouldn't be at level 2. 

Level 2 - Egg
Level 4 - Hatchling 
Level 8 - Turtle
Level 16 - Apprentice Sea Turtle
Level 32 - White Hawksbill
Level 48 - Yellow Snapping Turtle 
Level 64 - Blue Loggerhead
Level 80 - Black belt Leatherback
Level 96 - Galapagos Tortoise
Level 100 - Sage Archelon (largest sea turtle known to humans, extinct though)

**Comment by phate83** [comment]
lvl 2 - Egg
lvl 4 - Hatchling
lvl 8 - Turtle 
lvl 16 - Speckled Turtle
lvl 32 - Box Turtle
lvl 48 - Sea Turtle
lvl 64 - Snapping Turtle
lvl 80 - Leatherback Turtle
lvl 96 - Galapagos Turtle
lvl 100 - Your choice of one of the 4 TMNT (not splinter)

**Comment by TRTLAlien** [comment]
lvl 2 - Turtle Soup
lvl 4 - Koopa
lvl 8 - Young Turtle
lvl 16 - Teenage Ninja Turtle
lvl 32 - Juvenile Turtle
lvl 48 - Snap Back Turtle
lvl 64 - Genbu Turtle
lvl 80 - Kappa Turtle
lvl 96 - Maturin Turtle
lvl 100 - Wizard Turtle

**Comment by RocksteadyTC** [comment]
done
