### ISSUE TITLE
Feedback on API Docs

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/meta#99]
Hello Ladies and Gents!

API Docs are near completion and we would like your feedback on it before calling it done.

Site: https://hinata-104.shadow-clone-jutsu.com | ([GitHub](https://github.com/ar-x/turtlecoin-api-docs-site))

---
via tmac and me

**Comment by ar-x** [comment]
Make headers in the content area deep linkable. (like how they are via the left sidebar)

**Comment by ar-x** [comment]
replace `binded` with `bound`.

**Comment by dbileck** [comment]
Python requirement `pip install turtlecoin` is showing up for each of the languages (shell, javascript, php).

**Comment by SoreGums** [comment]
would you see one of these for any app that needs an API doc

or does it just grow to accommodate other apps APIs?

Like does the "introduction" become an intro to the fact that this page has APIs for x, y, z and then the left sidebar top-level headings are:

1. Introduction
2. Wallet RPC API
3. TurtleCoin Daemon API
4. Other API
5. Other API

or is there going to be an overall header/footer from the large #98 Docs frontend that links individually to each Apps API?

Hope this is clear.
Looks great.

**Comment by ar-x** [comment]
@SoreGums 

```
Like does the "introduction" become an intro to the fact that this page has APIs for x, y, z and then the left sidebar top-level headings are:

Introduction
Wallet RPC API
TurtleCoin Daemon API
Other API
Other API
```
That

We would have Wallet RPC, TurtleCoin Daemon RPC, and an Introduction explaining the broader context and relationships. A better version of _Integration with Bytecoin_ (https://wiki.bytecoin.org/wiki/Main_Page).

**Comment by SoreGums** [comment]
Nice one.

The thing I like about all projects on the GitHub org turtlecoin and the idea for the docs is that each project doesn't need to figure out how to do docs, they just start writing content in the existing place.

Having said that with Krang, I'm going to have a cli interface like [Docker's](https://docs.docker.com/engine/reference/commandline/cli/) and also some kind of HTTP API. These are going to be quite lengthy. So does it still make sense to have all in one or is it still possible to split things out or doesn't really matter?

Also while the C++ daemon is probably going to be re-written in C#, I think we should still preserve the C++ daemon and its docs. so how does that play into the One Page for all?

**Comment by ar-x** [comment]
@SoreGums Once those things land, we can extend this site in various ways based on what makes sense. One nice way is to have a landing page for APIs like: https://docs.bugsnag.com/api/.

**Comment by ZedPea** [comment]
I'd like to see some possible errors that can occur, for example, what does "Wrong Amount" mean when you have enough balance to send the transaction? These are mainly focused at sendTransaction(), but there are a couple of functions I have found which give odd error messages.

**Comment by ar-x** [comment]
> Having said that with Krang, I'm going to have a cli interface like Docker's and also some kind of HTTP API. These are going to be quite lengthy. So does it still make sense to have all in one or is it still possible to split things out or doesn't really matter?

@SoreGums This can be done via https://github.com/ar-x/turtlecoin-wiki/issues/12

**Comment by ar-x** [comment]
A quick update on the issues brought up here:

1. [x] Make headers in the content area deep linkable. (like how they are via the left sidebar)
2. [x] replace binded with bound (?).
3. [x] Python requirement pip install turtlecoin is showing up for each of the languages (shell, javascript, php).
4. [x] SoreGums's questions on long term uses - I believe these are now sorted out via a [separate discussion](https://github.com/ar-x/turtlecoin-wiki/issues/12).
5. [ ] via ZedPea I'd like to see some possible errors that can occur.


I believe (5) is the biggest one and probably the one with the most impact. Hopefully this is something we can add over time via devs who know more about this.

**Comment by ar-x** [comment]
Can I get an example of a good way to attribute the Bytecoin wiki. Currently, we just have a Creative Commons badge on the left sidebar bottom, which is probably not sufficient (?).

**Comment by ar-x** [comment]
@SoreGums Thanks. Done. Feel free to comment [here](https://github.com/ar-x/turtlecoin-api-docs-site/issues/6) in case there is anything else on this.

**Comment by ar-x** [comment]
Going to close this meta issue now. Looking at wrapping this up.
